// Copyright 2020 StrongDM Inc
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// 
// This file is necessary to keep the compiler happy. protoc_gen_swagger
// doesn't appear to generate Java files, so javac gets upset. We don't care
// about the swagger annotations at all, so this file just fills in the
// necessary gaps to make things compile.

// This file was generated by protogen. DO NOT EDIT.

package grpc.gateway.protoc_gen_swagger.options;

public class Annotations {
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      com.strongdm.api.v1.plumbing.Options.FieldOptions> openapiv2Operation = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.strongdm.api.v1.plumbing.Options.FieldOptions.class,
        com.strongdm.api.v1.plumbing.Options.FieldOptions.getDefaultInstance());
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      com.strongdm.api.v1.plumbing.Options.FieldOptions> openapiv2Schema = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.strongdm.api.v1.plumbing.Options.FieldOptions.class,
        com.strongdm.api.v1.plumbing.Options.FieldOptions.getDefaultInstance());
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      com.strongdm.api.v1.plumbing.Options.FieldOptions> openapiv2Field = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.strongdm.api.v1.plumbing.Options.FieldOptions.class,
        com.strongdm.api.v1.plumbing.Options.FieldOptions.getDefaultInstance());
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      com.strongdm.api.v1.plumbing.Options.FieldOptions> openapiv2Swagger = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.strongdm.api.v1.plumbing.Options.FieldOptions.class,
        com.strongdm.api.v1.plumbing.Options.FieldOptions.getDefaultInstance());
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(new String[]{},
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    openapiv2Operation.internalInit(com.strongdm.api.v1.plumbing.Options.fieldOptions.getDescriptor());
    openapiv2Schema.internalInit(com.strongdm.api.v1.plumbing.Options.fieldOptions.getDescriptor());
    openapiv2Field.internalInit(com.strongdm.api.v1.plumbing.Options.fieldOptions.getDescriptor());
    openapiv2Swagger.internalInit(com.strongdm.api.v1.plumbing.Options.fieldOptions.getDescriptor());
  }
}
