// Copyright 2020 StrongDM Inc
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// 
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resourcetypes.proto

package com.strongdm.api.plumbing;

public final class ResourceTypePlumbing {
  private ResourceTypePlumbing() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code v1.ResourceType}
   */
  public enum ResourceType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>RESOURCE_TYPE_UNSPECIFIED = 0;</code>
     */
    RESOURCE_TYPE_UNSPECIFIED(0),
    /**
     * <code>RESOURCE_TYPE_AKS = 805;</code>
     */
    RESOURCE_TYPE_AKS(805),
    /**
     * <code>RESOURCE_TYPE_AKS_BASIC_AUTH = 806;</code>
     */
    RESOURCE_TYPE_AKS_BASIC_AUTH(806),
    /**
     * <code>RESOURCE_TYPE_AKS_SERVICE_ACCOUNT = 807;</code>
     */
    RESOURCE_TYPE_AKS_SERVICE_ACCOUNT(807),
    /**
     * <code>RESOURCE_TYPE_AKS_SERVICE_ACCOUNT_USER_IMPERSONATION = 810;</code>
     */
    RESOURCE_TYPE_AKS_SERVICE_ACCOUNT_USER_IMPERSONATION(810),
    /**
     * <code>RESOURCE_TYPE_AKS_USER_IMPERSONATION = 814;</code>
     */
    RESOURCE_TYPE_AKS_USER_IMPERSONATION(814),
    /**
     * <code>RESOURCE_TYPE_AMAZON_MQAMQP = 2502;</code>
     */
    RESOURCE_TYPE_AMAZON_MQAMQP(2502),
    /**
     * <code>RESOURCE_TYPE_AWS = 2300;</code>
     */
    RESOURCE_TYPE_AWS(2300),
    /**
     * <code>RESOURCE_TYPE_AWS_CONSOLE = 3000;</code>
     */
    RESOURCE_TYPE_AWS_CONSOLE(3000),
    /**
     * <code>RESOURCE_TYPE_AWS_CONSOLE_STATIC_KEY_PAIR = 3001;</code>
     */
    RESOURCE_TYPE_AWS_CONSOLE_STATIC_KEY_PAIR(3001),
    /**
     * <code>RESOURCE_TYPE_AWS_INSTANCE_PROFILE = 2301;</code>
     */
    RESOURCE_TYPE_AWS_INSTANCE_PROFILE(2301),
    /**
     * <code>RESOURCE_TYPE_AEROSPIKE = 4600;</code>
     */
    RESOURCE_TYPE_AEROSPIKE(4600),
    /**
     * <code>RESOURCE_TYPE_AMAZON_EKS = 802;</code>
     */
    RESOURCE_TYPE_AMAZON_EKS(802),
    /**
     * <code>RESOURCE_TYPE_AMAZON_EKS_INSTANCE_PROFILE = 809;</code>
     */
    RESOURCE_TYPE_AMAZON_EKS_INSTANCE_PROFILE(809),
    /**
     * <code>RESOURCE_TYPE_AMAZON_EKS_INSTANCE_PROFILE_USER_IMPERSONATION = 813;</code>
     */
    RESOURCE_TYPE_AMAZON_EKS_INSTANCE_PROFILE_USER_IMPERSONATION(813),
    /**
     * <code>RESOURCE_TYPE_AMAZON_EKS_USER_IMPERSONATION = 818;</code>
     */
    RESOURCE_TYPE_AMAZON_EKS_USER_IMPERSONATION(818),
    /**
     * <code>RESOURCE_TYPE_AMAZON_ES = 600;</code>
     */
    RESOURCE_TYPE_AMAZON_ES(600),
    /**
     * <code>RESOURCE_TYPE_AMAZON_ESIAM = 602;</code>
     */
    RESOURCE_TYPE_AMAZON_ESIAM(602),
    /**
     * <code>RESOURCE_TYPE_AMAZON_MQAMQP_091 = 2501;</code>
     */
    RESOURCE_TYPE_AMAZON_MQAMQP_091(2501),
    /**
     * <code>RESOURCE_TYPE_ATHENA = 100;</code>
     */
    RESOURCE_TYPE_ATHENA(100),
    /**
     * <code>RESOURCE_TYPE_ATHENA_IAM = 3400;</code>
     */
    RESOURCE_TYPE_ATHENA_IAM(3400),
    /**
     * <code>RESOURCE_TYPE_AURORA_MY_SQL = 1101;</code>
     */
    RESOURCE_TYPE_AURORA_MY_SQL(1101),
    /**
     * <code>RESOURCE_TYPE_AURORA_MY_SQLIAM = 1109;</code>
     */
    RESOURCE_TYPE_AURORA_MY_SQLIAM(1109),
    /**
     * <code>RESOURCE_TYPE_AURORA_POSTGRES = 1301;</code>
     */
    RESOURCE_TYPE_AURORA_POSTGRES(1301),
    /**
     * <code>RESOURCE_TYPE_AURORA_POSTGRES_IAM = 1309;</code>
     */
    RESOURCE_TYPE_AURORA_POSTGRES_IAM(1309),
    /**
     * <code>RESOURCE_TYPE_AZURE = 2800;</code>
     */
    RESOURCE_TYPE_AZURE(2800),
    /**
     * <code>RESOURCE_TYPE_AZURE_CERT = 2801;</code>
     */
    RESOURCE_TYPE_AZURE_CERT(2801),
    /**
     * <code>RESOURCE_TYPE_AZURE_MY_SQL = 1107;</code>
     */
    RESOURCE_TYPE_AZURE_MY_SQL(1107),
    /**
     * <code>RESOURCE_TYPE_AZURE_MY_SQL_MANAGED_IDENTITY = 1110;</code>
     */
    RESOURCE_TYPE_AZURE_MY_SQL_MANAGED_IDENTITY(1110),
    /**
     * <code>RESOURCE_TYPE_AZURE_POSTGRES = 1307;</code>
     */
    RESOURCE_TYPE_AZURE_POSTGRES(1307),
    /**
     * <code>RESOURCE_TYPE_AZURE_POSTGRES_MANAGED_IDENTITY = 1308;</code>
     */
    RESOURCE_TYPE_AZURE_POSTGRES_MANAGED_IDENTITY(1308),
    /**
     * <code>RESOURCE_TYPE_BIGQUERY = 200;</code>
     */
    RESOURCE_TYPE_BIGQUERY(200),
    /**
     * <code>RESOURCE_TYPE_CASSANDRA = 300;</code>
     */
    RESOURCE_TYPE_CASSANDRA(300),
    /**
     * <code>RESOURCE_TYPE_CITUS = 1305;</code>
     */
    RESOURCE_TYPE_CITUS(1305),
    /**
     * <code>RESOURCE_TYPE_CLICK_HOUSE_HTTP = 5;</code>
     */
    RESOURCE_TYPE_CLICK_HOUSE_HTTP(5),
    /**
     * <code>RESOURCE_TYPE_CLICK_HOUSE_MY_SQL = 1108;</code>
     */
    RESOURCE_TYPE_CLICK_HOUSE_MY_SQL(1108),
    /**
     * <code>RESOURCE_TYPE_CLICK_HOUSE_TCP = 6;</code>
     */
    RESOURCE_TYPE_CLICK_HOUSE_TCP(6),
    /**
     * <code>RESOURCE_TYPE_CLUSTRIX = 1102;</code>
     */
    RESOURCE_TYPE_CLUSTRIX(1102),
    /**
     * <code>RESOURCE_TYPE_COCKROACH = 1303;</code>
     */
    RESOURCE_TYPE_COCKROACH(1303),
    /**
     * <code>RESOURCE_TYPE_COUCHBASE_DATABASE = 3201;</code>
     */
    RESOURCE_TYPE_COUCHBASE_DATABASE(3201),
    /**
     * <code>RESOURCE_TYPE_COUCHBASE_WEB_UI = 3200;</code>
     */
    RESOURCE_TYPE_COUCHBASE_WEB_UI(3200),
    /**
     * <code>RESOURCE_TYPE_DB_2_I = 2400;</code>
     */
    RESOURCE_TYPE_DB_2_I(2400),
    /**
     * <code>RESOURCE_TYPE_DB_2_LUW = 2200;</code>
     */
    RESOURCE_TYPE_DB_2_LUW(2200),
    /**
     * <code>RESOURCE_TYPE_DOCUMENT_DB_HOST = 1052;</code>
     */
    RESOURCE_TYPE_DOCUMENT_DB_HOST(1052),
    /**
     * <code>RESOURCE_TYPE_DOCUMENT_DB_HOST_IAM = 1055;</code>
     */
    RESOURCE_TYPE_DOCUMENT_DB_HOST_IAM(1055),
    /**
     * <code>RESOURCE_TYPE_DOCUMENT_DB_REPLICA_SET = 1053;</code>
     */
    RESOURCE_TYPE_DOCUMENT_DB_REPLICA_SET(1053),
    /**
     * <code>RESOURCE_TYPE_DOCUMENT_DB_REPLICA_SET_IAM = 1056;</code>
     */
    RESOURCE_TYPE_DOCUMENT_DB_REPLICA_SET_IAM(1056),
    /**
     * <code>RESOURCE_TYPE_DRUID = 400;</code>
     */
    RESOURCE_TYPE_DRUID(400),
    /**
     * <code>RESOURCE_TYPE_DYNAMO_DB = 500;</code>
     */
    RESOURCE_TYPE_DYNAMO_DB(500),
    /**
     * <code>RESOURCE_TYPE_DYNAMO_DBIAM = 501;</code>
     */
    RESOURCE_TYPE_DYNAMO_DBIAM(501),
    /**
     * <code>RESOURCE_TYPE_ELASTIC = 601;</code>
     */
    RESOURCE_TYPE_ELASTIC(601),
    /**
     * <code>RESOURCE_TYPE_ELASTI_CACHE_REDIS = 1601;</code>
     */
    RESOURCE_TYPE_ELASTI_CACHE_REDIS(1601),
    /**
     * <code>RESOURCE_TYPE_ELASTI_CACHE_REDIS_IAM = 1603;</code>
     */
    RESOURCE_TYPE_ELASTI_CACHE_REDIS_IAM(1603),
    /**
     * <code>RESOURCE_TYPE_ENTRA_ID = 2803;</code>
     */
    RESOURCE_TYPE_ENTRA_ID(2803),
    /**
     * <code>RESOURCE_TYPE_GCP = 2700;</code>
     */
    RESOURCE_TYPE_GCP(2700),
    /**
     * <code>RESOURCE_TYPE_GCP_CONSOLE = 3300;</code>
     */
    RESOURCE_TYPE_GCP_CONSOLE(3300),
    /**
     * <code>RESOURCE_TYPE_GCPWIF = 2701;</code>
     */
    RESOURCE_TYPE_GCPWIF(2701),
    /**
     * <code>RESOURCE_TYPE_GIT_HUB = 3301;</code>
     */
    RESOURCE_TYPE_GIT_HUB(3301),
    /**
     * <code>RESOURCE_TYPE_GOOGLE_ADMIN = 3302;</code>
     */
    RESOURCE_TYPE_GOOGLE_ADMIN(3302),
    /**
     * <code>RESOURCE_TYPE_GOOGLE_GKE = 803;</code>
     */
    RESOURCE_TYPE_GOOGLE_GKE(803),
    /**
     * <code>RESOURCE_TYPE_GOOGLE_GKE_USER_IMPERSONATION = 816;</code>
     */
    RESOURCE_TYPE_GOOGLE_GKE_USER_IMPERSONATION(816),
    /**
     * <code>RESOURCE_TYPE_GOOGLE_SPANNER = 4800;</code>
     */
    RESOURCE_TYPE_GOOGLE_SPANNER(4800),
    /**
     * <code>RESOURCE_TYPE_GREENPLUM = 1302;</code>
     */
    RESOURCE_TYPE_GREENPLUM(1302),
    /**
     * <code>RESOURCE_TYPE_HTTP_AUTH = 702;</code>
     */
    RESOURCE_TYPE_HTTP_AUTH(702),
    /**
     * <code>RESOURCE_TYPE_HTTP_BASIC = 700;</code>
     */
    RESOURCE_TYPE_HTTP_BASIC(700),
    /**
     * <code>RESOURCE_TYPE_HTTP_NO_AUTH = 701;</code>
     */
    RESOURCE_TYPE_HTTP_NO_AUTH(701),
    /**
     * <code>RESOURCE_TYPE_KUBERNETES = 800;</code>
     */
    RESOURCE_TYPE_KUBERNETES(800),
    /**
     * <code>RESOURCE_TYPE_KUBERNETES_BASIC_AUTH = 801;</code>
     */
    RESOURCE_TYPE_KUBERNETES_BASIC_AUTH(801),
    /**
     * <code>RESOURCE_TYPE_KUBERNETES_POD_IDENTITY = 819;</code>
     */
    RESOURCE_TYPE_KUBERNETES_POD_IDENTITY(819),
    /**
     * <code>RESOURCE_TYPE_KUBERNETES_SERVICE_ACCOUNT = 804;</code>
     */
    RESOURCE_TYPE_KUBERNETES_SERVICE_ACCOUNT(804),
    /**
     * <code>RESOURCE_TYPE_KUBERNETES_SERVICE_ACCOUNT_USER_IMPERSONATION = 808;</code>
     */
    RESOURCE_TYPE_KUBERNETES_SERVICE_ACCOUNT_USER_IMPERSONATION(808),
    /**
     * <code>RESOURCE_TYPE_KUBERNETES_USER_IMPERSONATION = 812;</code>
     */
    RESOURCE_TYPE_KUBERNETES_USER_IMPERSONATION(812),
    /**
     * <code>RESOURCE_TYPE_MCP = 4700;</code>
     */
    RESOURCE_TYPE_MCP(4700),
    /**
     * <code>RESOURCE_TYPE_MCPDCR = 4701;</code>
     */
    RESOURCE_TYPE_MCPDCR(4701),
    /**
     * <code>RESOURCE_TYPE_MTLS_MY_SQL = 1106;</code>
     */
    RESOURCE_TYPE_MTLS_MY_SQL(1106),
    /**
     * <code>RESOURCE_TYPE_MTLS_POSTGRES = 1306;</code>
     */
    RESOURCE_TYPE_MTLS_POSTGRES(1306),
    /**
     * <code>RESOURCE_TYPE_MARIA = 1103;</code>
     */
    RESOURCE_TYPE_MARIA(1103),
    /**
     * <code>RESOURCE_TYPE_MEMCACHED = 900;</code>
     */
    RESOURCE_TYPE_MEMCACHED(900),
    /**
     * <code>RESOURCE_TYPE_MEM_SQL = 1104;</code>
     */
    RESOURCE_TYPE_MEM_SQL(1104),
    /**
     * <code>RESOURCE_TYPE_MICROSOFT_365 = 3303;</code>
     */
    RESOURCE_TYPE_MICROSOFT_365(3303),
    /**
     * <code>RESOURCE_TYPE_MONGO_DB_HOST = 1002;</code>
     */
    RESOURCE_TYPE_MONGO_DB_HOST(1002),
    /**
     * <code>RESOURCE_TYPE_MONGO_DB = 1000;</code>
     */
    RESOURCE_TYPE_MONGO_DB(1000),
    /**
     * <code>RESOURCE_TYPE_MONGO_DB_LEGACY_REPLICA_SET = 1001;</code>
     */
    RESOURCE_TYPE_MONGO_DB_LEGACY_REPLICA_SET(1001),
    /**
     * <code>RESOURCE_TYPE_MONGO_DB_REPLICA_SET = 1003;</code>
     */
    RESOURCE_TYPE_MONGO_DB_REPLICA_SET(1003),
    /**
     * <code>RESOURCE_TYPE_MONGO_DB_SHARDED_CLUSTER = 1054;</code>
     */
    RESOURCE_TYPE_MONGO_DB_SHARDED_CLUSTER(1054),
    /**
     * <code>RESOURCE_TYPE_MY_SQL = 1100;</code>
     */
    RESOURCE_TYPE_MY_SQL(1100),
    /**
     * <code>RESOURCE_TYPE_NEPTUNE = 2250;</code>
     */
    RESOURCE_TYPE_NEPTUNE(2250),
    /**
     * <code>RESOURCE_TYPE_NEPTUNE_IAM = 2201;</code>
     */
    RESOURCE_TYPE_NEPTUNE_IAM(2201),
    /**
     * <code>RESOURCE_TYPE_OKTA_ADMIN = 3304;</code>
     */
    RESOURCE_TYPE_OKTA_ADMIN(3304),
    /**
     * <code>RESOURCE_TYPE_OKTA_GROUPS = 3500;</code>
     */
    RESOURCE_TYPE_OKTA_GROUPS(3500),
    /**
     * <code>RESOURCE_TYPE_ORACLE = 1200;</code>
     */
    RESOURCE_TYPE_ORACLE(1200),
    /**
     * <code>RESOURCE_TYPE_ORACLE_NNE = 1201;</code>
     */
    RESOURCE_TYPE_ORACLE_NNE(1201),
    /**
     * <code>RESOURCE_TYPE_POSTGRES = 1300;</code>
     */
    RESOURCE_TYPE_POSTGRES(1300),
    /**
     * <code>RESOURCE_TYPE_PRESTO = 1400;</code>
     */
    RESOURCE_TYPE_PRESTO(1400),
    /**
     * <code>RESOURCE_TYPE_RDP = 1500;</code>
     */
    RESOURCE_TYPE_RDP(1500),
    /**
     * <code>RESOURCE_TYPE_RDP_CERT = 1501;</code>
     */
    RESOURCE_TYPE_RDP_CERT(1501),
    /**
     * <code>RESOURCE_TYPE_RDS_POSTGRES_IAM = 1310;</code>
     */
    RESOURCE_TYPE_RDS_POSTGRES_IAM(1310),
    /**
     * <code>RESOURCE_TYPE_RABBIT_MQAMQP_091 = 2500;</code>
     */
    RESOURCE_TYPE_RABBIT_MQAMQP_091(2500),
    /**
     * <code>RESOURCE_TYPE_TCP = 2600;</code>
     */
    RESOURCE_TYPE_TCP(2600),
    /**
     * <code>RESOURCE_TYPE_REDIS = 1600;</code>
     */
    RESOURCE_TYPE_REDIS(1600),
    /**
     * <code>RESOURCE_TYPE_REDIS_CLUSTER = 1602;</code>
     */
    RESOURCE_TYPE_REDIS_CLUSTER(1602),
    /**
     * <code>RESOURCE_TYPE_REDSHIFT = 1304;</code>
     */
    RESOURCE_TYPE_REDSHIFT(1304),
    /**
     * <code>RESOURCE_TYPE_REDSHIFT_IAM = 1312;</code>
     */
    RESOURCE_TYPE_REDSHIFT_IAM(1312),
    /**
     * <code>RESOURCE_TYPE_REDSHIFT_SERVERLESS_IAM = 1311;</code>
     */
    RESOURCE_TYPE_REDSHIFT_SERVERLESS_IAM(1311),
    /**
     * <code>RESOURCE_TYPE_SQL_SERVER = 1800;</code>
     */
    RESOURCE_TYPE_SQL_SERVER(1800),
    /**
     * <code>RESOURCE_TYPE_SQL_SERVER_AZURE_AD = 1805;</code>
     */
    RESOURCE_TYPE_SQL_SERVER_AZURE_AD(1805),
    /**
     * <code>RESOURCE_TYPE_SQL_SERVER_KERBEROS = 1810;</code>
     */
    RESOURCE_TYPE_SQL_SERVER_KERBEROS(1810),
    /**
     * <code>RESOURCE_TYPE_SSH = 1900;</code>
     */
    RESOURCE_TYPE_SSH(1900),
    /**
     * <code>RESOURCE_TYPE_SSH_CERT = 1901;</code>
     */
    RESOURCE_TYPE_SSH_CERT(1901),
    /**
     * <code>RESOURCE_TYPE_SSH_CERT_USER_PROVISION = 1903;</code>
     */
    RESOURCE_TYPE_SSH_CERT_USER_PROVISION(1903),
    /**
     * <code>RESOURCE_TYPE_SSH_CUSTOMER_KEY = 1902;</code>
     */
    RESOURCE_TYPE_SSH_CUSTOMER_KEY(1902),
    /**
     * <code>RESOURCE_TYPE_SSH_PASSWORD = 1904;</code>
     */
    RESOURCE_TYPE_SSH_PASSWORD(1904),
    /**
     * <code>RESOURCE_TYPE_SALESFORCE = 3305;</code>
     */
    RESOURCE_TYPE_SALESFORCE(3305),
    /**
     * <code>RESOURCE_TYPE_SINGLE_STORE = 1105;</code>
     */
    RESOURCE_TYPE_SINGLE_STORE(1105),
    /**
     * <code>RESOURCE_TYPE_SNOWFLAKE = 1700;</code>
     */
    RESOURCE_TYPE_SNOWFLAKE(1700),
    /**
     * <code>RESOURCE_TYPE_SNOWSIGHT = 1701;</code>
     */
    RESOURCE_TYPE_SNOWSIGHT(1701),
    /**
     * <code>RESOURCE_TYPE_SYBASE_ASE = 2000;</code>
     */
    RESOURCE_TYPE_SYBASE_ASE(2000),
    /**
     * <code>RESOURCE_TYPE_SYBASE_IQ = 2001;</code>
     */
    RESOURCE_TYPE_SYBASE_IQ(2001),
    /**
     * <code>RESOURCE_TYPE_TERADATA = 2100;</code>
     */
    RESOURCE_TYPE_TERADATA(2100),
    /**
     * <code>RESOURCE_TYPE_TRINO = 1401;</code>
     */
    RESOURCE_TYPE_TRINO(1401),
    /**
     * <code>RESOURCE_TYPE_VERTICA = 4500;</code>
     */
    RESOURCE_TYPE_VERTICA(4500),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>RESOURCE_TYPE_UNSPECIFIED = 0;</code>
     */
    public static final int RESOURCE_TYPE_UNSPECIFIED_VALUE = 0;
    /**
     * <code>RESOURCE_TYPE_AKS = 805;</code>
     */
    public static final int RESOURCE_TYPE_AKS_VALUE = 805;
    /**
     * <code>RESOURCE_TYPE_AKS_BASIC_AUTH = 806;</code>
     */
    public static final int RESOURCE_TYPE_AKS_BASIC_AUTH_VALUE = 806;
    /**
     * <code>RESOURCE_TYPE_AKS_SERVICE_ACCOUNT = 807;</code>
     */
    public static final int RESOURCE_TYPE_AKS_SERVICE_ACCOUNT_VALUE = 807;
    /**
     * <code>RESOURCE_TYPE_AKS_SERVICE_ACCOUNT_USER_IMPERSONATION = 810;</code>
     */
    public static final int RESOURCE_TYPE_AKS_SERVICE_ACCOUNT_USER_IMPERSONATION_VALUE = 810;
    /**
     * <code>RESOURCE_TYPE_AKS_USER_IMPERSONATION = 814;</code>
     */
    public static final int RESOURCE_TYPE_AKS_USER_IMPERSONATION_VALUE = 814;
    /**
     * <code>RESOURCE_TYPE_AMAZON_MQAMQP = 2502;</code>
     */
    public static final int RESOURCE_TYPE_AMAZON_MQAMQP_VALUE = 2502;
    /**
     * <code>RESOURCE_TYPE_AWS = 2300;</code>
     */
    public static final int RESOURCE_TYPE_AWS_VALUE = 2300;
    /**
     * <code>RESOURCE_TYPE_AWS_CONSOLE = 3000;</code>
     */
    public static final int RESOURCE_TYPE_AWS_CONSOLE_VALUE = 3000;
    /**
     * <code>RESOURCE_TYPE_AWS_CONSOLE_STATIC_KEY_PAIR = 3001;</code>
     */
    public static final int RESOURCE_TYPE_AWS_CONSOLE_STATIC_KEY_PAIR_VALUE = 3001;
    /**
     * <code>RESOURCE_TYPE_AWS_INSTANCE_PROFILE = 2301;</code>
     */
    public static final int RESOURCE_TYPE_AWS_INSTANCE_PROFILE_VALUE = 2301;
    /**
     * <code>RESOURCE_TYPE_AEROSPIKE = 4600;</code>
     */
    public static final int RESOURCE_TYPE_AEROSPIKE_VALUE = 4600;
    /**
     * <code>RESOURCE_TYPE_AMAZON_EKS = 802;</code>
     */
    public static final int RESOURCE_TYPE_AMAZON_EKS_VALUE = 802;
    /**
     * <code>RESOURCE_TYPE_AMAZON_EKS_INSTANCE_PROFILE = 809;</code>
     */
    public static final int RESOURCE_TYPE_AMAZON_EKS_INSTANCE_PROFILE_VALUE = 809;
    /**
     * <code>RESOURCE_TYPE_AMAZON_EKS_INSTANCE_PROFILE_USER_IMPERSONATION = 813;</code>
     */
    public static final int RESOURCE_TYPE_AMAZON_EKS_INSTANCE_PROFILE_USER_IMPERSONATION_VALUE = 813;
    /**
     * <code>RESOURCE_TYPE_AMAZON_EKS_USER_IMPERSONATION = 818;</code>
     */
    public static final int RESOURCE_TYPE_AMAZON_EKS_USER_IMPERSONATION_VALUE = 818;
    /**
     * <code>RESOURCE_TYPE_AMAZON_ES = 600;</code>
     */
    public static final int RESOURCE_TYPE_AMAZON_ES_VALUE = 600;
    /**
     * <code>RESOURCE_TYPE_AMAZON_ESIAM = 602;</code>
     */
    public static final int RESOURCE_TYPE_AMAZON_ESIAM_VALUE = 602;
    /**
     * <code>RESOURCE_TYPE_AMAZON_MQAMQP_091 = 2501;</code>
     */
    public static final int RESOURCE_TYPE_AMAZON_MQAMQP_091_VALUE = 2501;
    /**
     * <code>RESOURCE_TYPE_ATHENA = 100;</code>
     */
    public static final int RESOURCE_TYPE_ATHENA_VALUE = 100;
    /**
     * <code>RESOURCE_TYPE_ATHENA_IAM = 3400;</code>
     */
    public static final int RESOURCE_TYPE_ATHENA_IAM_VALUE = 3400;
    /**
     * <code>RESOURCE_TYPE_AURORA_MY_SQL = 1101;</code>
     */
    public static final int RESOURCE_TYPE_AURORA_MY_SQL_VALUE = 1101;
    /**
     * <code>RESOURCE_TYPE_AURORA_MY_SQLIAM = 1109;</code>
     */
    public static final int RESOURCE_TYPE_AURORA_MY_SQLIAM_VALUE = 1109;
    /**
     * <code>RESOURCE_TYPE_AURORA_POSTGRES = 1301;</code>
     */
    public static final int RESOURCE_TYPE_AURORA_POSTGRES_VALUE = 1301;
    /**
     * <code>RESOURCE_TYPE_AURORA_POSTGRES_IAM = 1309;</code>
     */
    public static final int RESOURCE_TYPE_AURORA_POSTGRES_IAM_VALUE = 1309;
    /**
     * <code>RESOURCE_TYPE_AZURE = 2800;</code>
     */
    public static final int RESOURCE_TYPE_AZURE_VALUE = 2800;
    /**
     * <code>RESOURCE_TYPE_AZURE_CERT = 2801;</code>
     */
    public static final int RESOURCE_TYPE_AZURE_CERT_VALUE = 2801;
    /**
     * <code>RESOURCE_TYPE_AZURE_MY_SQL = 1107;</code>
     */
    public static final int RESOURCE_TYPE_AZURE_MY_SQL_VALUE = 1107;
    /**
     * <code>RESOURCE_TYPE_AZURE_MY_SQL_MANAGED_IDENTITY = 1110;</code>
     */
    public static final int RESOURCE_TYPE_AZURE_MY_SQL_MANAGED_IDENTITY_VALUE = 1110;
    /**
     * <code>RESOURCE_TYPE_AZURE_POSTGRES = 1307;</code>
     */
    public static final int RESOURCE_TYPE_AZURE_POSTGRES_VALUE = 1307;
    /**
     * <code>RESOURCE_TYPE_AZURE_POSTGRES_MANAGED_IDENTITY = 1308;</code>
     */
    public static final int RESOURCE_TYPE_AZURE_POSTGRES_MANAGED_IDENTITY_VALUE = 1308;
    /**
     * <code>RESOURCE_TYPE_BIGQUERY = 200;</code>
     */
    public static final int RESOURCE_TYPE_BIGQUERY_VALUE = 200;
    /**
     * <code>RESOURCE_TYPE_CASSANDRA = 300;</code>
     */
    public static final int RESOURCE_TYPE_CASSANDRA_VALUE = 300;
    /**
     * <code>RESOURCE_TYPE_CITUS = 1305;</code>
     */
    public static final int RESOURCE_TYPE_CITUS_VALUE = 1305;
    /**
     * <code>RESOURCE_TYPE_CLICK_HOUSE_HTTP = 5;</code>
     */
    public static final int RESOURCE_TYPE_CLICK_HOUSE_HTTP_VALUE = 5;
    /**
     * <code>RESOURCE_TYPE_CLICK_HOUSE_MY_SQL = 1108;</code>
     */
    public static final int RESOURCE_TYPE_CLICK_HOUSE_MY_SQL_VALUE = 1108;
    /**
     * <code>RESOURCE_TYPE_CLICK_HOUSE_TCP = 6;</code>
     */
    public static final int RESOURCE_TYPE_CLICK_HOUSE_TCP_VALUE = 6;
    /**
     * <code>RESOURCE_TYPE_CLUSTRIX = 1102;</code>
     */
    public static final int RESOURCE_TYPE_CLUSTRIX_VALUE = 1102;
    /**
     * <code>RESOURCE_TYPE_COCKROACH = 1303;</code>
     */
    public static final int RESOURCE_TYPE_COCKROACH_VALUE = 1303;
    /**
     * <code>RESOURCE_TYPE_COUCHBASE_DATABASE = 3201;</code>
     */
    public static final int RESOURCE_TYPE_COUCHBASE_DATABASE_VALUE = 3201;
    /**
     * <code>RESOURCE_TYPE_COUCHBASE_WEB_UI = 3200;</code>
     */
    public static final int RESOURCE_TYPE_COUCHBASE_WEB_UI_VALUE = 3200;
    /**
     * <code>RESOURCE_TYPE_DB_2_I = 2400;</code>
     */
    public static final int RESOURCE_TYPE_DB_2_I_VALUE = 2400;
    /**
     * <code>RESOURCE_TYPE_DB_2_LUW = 2200;</code>
     */
    public static final int RESOURCE_TYPE_DB_2_LUW_VALUE = 2200;
    /**
     * <code>RESOURCE_TYPE_DOCUMENT_DB_HOST = 1052;</code>
     */
    public static final int RESOURCE_TYPE_DOCUMENT_DB_HOST_VALUE = 1052;
    /**
     * <code>RESOURCE_TYPE_DOCUMENT_DB_HOST_IAM = 1055;</code>
     */
    public static final int RESOURCE_TYPE_DOCUMENT_DB_HOST_IAM_VALUE = 1055;
    /**
     * <code>RESOURCE_TYPE_DOCUMENT_DB_REPLICA_SET = 1053;</code>
     */
    public static final int RESOURCE_TYPE_DOCUMENT_DB_REPLICA_SET_VALUE = 1053;
    /**
     * <code>RESOURCE_TYPE_DOCUMENT_DB_REPLICA_SET_IAM = 1056;</code>
     */
    public static final int RESOURCE_TYPE_DOCUMENT_DB_REPLICA_SET_IAM_VALUE = 1056;
    /**
     * <code>RESOURCE_TYPE_DRUID = 400;</code>
     */
    public static final int RESOURCE_TYPE_DRUID_VALUE = 400;
    /**
     * <code>RESOURCE_TYPE_DYNAMO_DB = 500;</code>
     */
    public static final int RESOURCE_TYPE_DYNAMO_DB_VALUE = 500;
    /**
     * <code>RESOURCE_TYPE_DYNAMO_DBIAM = 501;</code>
     */
    public static final int RESOURCE_TYPE_DYNAMO_DBIAM_VALUE = 501;
    /**
     * <code>RESOURCE_TYPE_ELASTIC = 601;</code>
     */
    public static final int RESOURCE_TYPE_ELASTIC_VALUE = 601;
    /**
     * <code>RESOURCE_TYPE_ELASTI_CACHE_REDIS = 1601;</code>
     */
    public static final int RESOURCE_TYPE_ELASTI_CACHE_REDIS_VALUE = 1601;
    /**
     * <code>RESOURCE_TYPE_ELASTI_CACHE_REDIS_IAM = 1603;</code>
     */
    public static final int RESOURCE_TYPE_ELASTI_CACHE_REDIS_IAM_VALUE = 1603;
    /**
     * <code>RESOURCE_TYPE_ENTRA_ID = 2803;</code>
     */
    public static final int RESOURCE_TYPE_ENTRA_ID_VALUE = 2803;
    /**
     * <code>RESOURCE_TYPE_GCP = 2700;</code>
     */
    public static final int RESOURCE_TYPE_GCP_VALUE = 2700;
    /**
     * <code>RESOURCE_TYPE_GCP_CONSOLE = 3300;</code>
     */
    public static final int RESOURCE_TYPE_GCP_CONSOLE_VALUE = 3300;
    /**
     * <code>RESOURCE_TYPE_GCPWIF = 2701;</code>
     */
    public static final int RESOURCE_TYPE_GCPWIF_VALUE = 2701;
    /**
     * <code>RESOURCE_TYPE_GIT_HUB = 3301;</code>
     */
    public static final int RESOURCE_TYPE_GIT_HUB_VALUE = 3301;
    /**
     * <code>RESOURCE_TYPE_GOOGLE_ADMIN = 3302;</code>
     */
    public static final int RESOURCE_TYPE_GOOGLE_ADMIN_VALUE = 3302;
    /**
     * <code>RESOURCE_TYPE_GOOGLE_GKE = 803;</code>
     */
    public static final int RESOURCE_TYPE_GOOGLE_GKE_VALUE = 803;
    /**
     * <code>RESOURCE_TYPE_GOOGLE_GKE_USER_IMPERSONATION = 816;</code>
     */
    public static final int RESOURCE_TYPE_GOOGLE_GKE_USER_IMPERSONATION_VALUE = 816;
    /**
     * <code>RESOURCE_TYPE_GOOGLE_SPANNER = 4800;</code>
     */
    public static final int RESOURCE_TYPE_GOOGLE_SPANNER_VALUE = 4800;
    /**
     * <code>RESOURCE_TYPE_GREENPLUM = 1302;</code>
     */
    public static final int RESOURCE_TYPE_GREENPLUM_VALUE = 1302;
    /**
     * <code>RESOURCE_TYPE_HTTP_AUTH = 702;</code>
     */
    public static final int RESOURCE_TYPE_HTTP_AUTH_VALUE = 702;
    /**
     * <code>RESOURCE_TYPE_HTTP_BASIC = 700;</code>
     */
    public static final int RESOURCE_TYPE_HTTP_BASIC_VALUE = 700;
    /**
     * <code>RESOURCE_TYPE_HTTP_NO_AUTH = 701;</code>
     */
    public static final int RESOURCE_TYPE_HTTP_NO_AUTH_VALUE = 701;
    /**
     * <code>RESOURCE_TYPE_KUBERNETES = 800;</code>
     */
    public static final int RESOURCE_TYPE_KUBERNETES_VALUE = 800;
    /**
     * <code>RESOURCE_TYPE_KUBERNETES_BASIC_AUTH = 801;</code>
     */
    public static final int RESOURCE_TYPE_KUBERNETES_BASIC_AUTH_VALUE = 801;
    /**
     * <code>RESOURCE_TYPE_KUBERNETES_POD_IDENTITY = 819;</code>
     */
    public static final int RESOURCE_TYPE_KUBERNETES_POD_IDENTITY_VALUE = 819;
    /**
     * <code>RESOURCE_TYPE_KUBERNETES_SERVICE_ACCOUNT = 804;</code>
     */
    public static final int RESOURCE_TYPE_KUBERNETES_SERVICE_ACCOUNT_VALUE = 804;
    /**
     * <code>RESOURCE_TYPE_KUBERNETES_SERVICE_ACCOUNT_USER_IMPERSONATION = 808;</code>
     */
    public static final int RESOURCE_TYPE_KUBERNETES_SERVICE_ACCOUNT_USER_IMPERSONATION_VALUE = 808;
    /**
     * <code>RESOURCE_TYPE_KUBERNETES_USER_IMPERSONATION = 812;</code>
     */
    public static final int RESOURCE_TYPE_KUBERNETES_USER_IMPERSONATION_VALUE = 812;
    /**
     * <code>RESOURCE_TYPE_MCP = 4700;</code>
     */
    public static final int RESOURCE_TYPE_MCP_VALUE = 4700;
    /**
     * <code>RESOURCE_TYPE_MCPDCR = 4701;</code>
     */
    public static final int RESOURCE_TYPE_MCPDCR_VALUE = 4701;
    /**
     * <code>RESOURCE_TYPE_MTLS_MY_SQL = 1106;</code>
     */
    public static final int RESOURCE_TYPE_MTLS_MY_SQL_VALUE = 1106;
    /**
     * <code>RESOURCE_TYPE_MTLS_POSTGRES = 1306;</code>
     */
    public static final int RESOURCE_TYPE_MTLS_POSTGRES_VALUE = 1306;
    /**
     * <code>RESOURCE_TYPE_MARIA = 1103;</code>
     */
    public static final int RESOURCE_TYPE_MARIA_VALUE = 1103;
    /**
     * <code>RESOURCE_TYPE_MEMCACHED = 900;</code>
     */
    public static final int RESOURCE_TYPE_MEMCACHED_VALUE = 900;
    /**
     * <code>RESOURCE_TYPE_MEM_SQL = 1104;</code>
     */
    public static final int RESOURCE_TYPE_MEM_SQL_VALUE = 1104;
    /**
     * <code>RESOURCE_TYPE_MICROSOFT_365 = 3303;</code>
     */
    public static final int RESOURCE_TYPE_MICROSOFT_365_VALUE = 3303;
    /**
     * <code>RESOURCE_TYPE_MONGO_DB_HOST = 1002;</code>
     */
    public static final int RESOURCE_TYPE_MONGO_DB_HOST_VALUE = 1002;
    /**
     * <code>RESOURCE_TYPE_MONGO_DB = 1000;</code>
     */
    public static final int RESOURCE_TYPE_MONGO_DB_VALUE = 1000;
    /**
     * <code>RESOURCE_TYPE_MONGO_DB_LEGACY_REPLICA_SET = 1001;</code>
     */
    public static final int RESOURCE_TYPE_MONGO_DB_LEGACY_REPLICA_SET_VALUE = 1001;
    /**
     * <code>RESOURCE_TYPE_MONGO_DB_REPLICA_SET = 1003;</code>
     */
    public static final int RESOURCE_TYPE_MONGO_DB_REPLICA_SET_VALUE = 1003;
    /**
     * <code>RESOURCE_TYPE_MONGO_DB_SHARDED_CLUSTER = 1054;</code>
     */
    public static final int RESOURCE_TYPE_MONGO_DB_SHARDED_CLUSTER_VALUE = 1054;
    /**
     * <code>RESOURCE_TYPE_MY_SQL = 1100;</code>
     */
    public static final int RESOURCE_TYPE_MY_SQL_VALUE = 1100;
    /**
     * <code>RESOURCE_TYPE_NEPTUNE = 2250;</code>
     */
    public static final int RESOURCE_TYPE_NEPTUNE_VALUE = 2250;
    /**
     * <code>RESOURCE_TYPE_NEPTUNE_IAM = 2201;</code>
     */
    public static final int RESOURCE_TYPE_NEPTUNE_IAM_VALUE = 2201;
    /**
     * <code>RESOURCE_TYPE_OKTA_ADMIN = 3304;</code>
     */
    public static final int RESOURCE_TYPE_OKTA_ADMIN_VALUE = 3304;
    /**
     * <code>RESOURCE_TYPE_OKTA_GROUPS = 3500;</code>
     */
    public static final int RESOURCE_TYPE_OKTA_GROUPS_VALUE = 3500;
    /**
     * <code>RESOURCE_TYPE_ORACLE = 1200;</code>
     */
    public static final int RESOURCE_TYPE_ORACLE_VALUE = 1200;
    /**
     * <code>RESOURCE_TYPE_ORACLE_NNE = 1201;</code>
     */
    public static final int RESOURCE_TYPE_ORACLE_NNE_VALUE = 1201;
    /**
     * <code>RESOURCE_TYPE_POSTGRES = 1300;</code>
     */
    public static final int RESOURCE_TYPE_POSTGRES_VALUE = 1300;
    /**
     * <code>RESOURCE_TYPE_PRESTO = 1400;</code>
     */
    public static final int RESOURCE_TYPE_PRESTO_VALUE = 1400;
    /**
     * <code>RESOURCE_TYPE_RDP = 1500;</code>
     */
    public static final int RESOURCE_TYPE_RDP_VALUE = 1500;
    /**
     * <code>RESOURCE_TYPE_RDP_CERT = 1501;</code>
     */
    public static final int RESOURCE_TYPE_RDP_CERT_VALUE = 1501;
    /**
     * <code>RESOURCE_TYPE_RDS_POSTGRES_IAM = 1310;</code>
     */
    public static final int RESOURCE_TYPE_RDS_POSTGRES_IAM_VALUE = 1310;
    /**
     * <code>RESOURCE_TYPE_RABBIT_MQAMQP_091 = 2500;</code>
     */
    public static final int RESOURCE_TYPE_RABBIT_MQAMQP_091_VALUE = 2500;
    /**
     * <code>RESOURCE_TYPE_TCP = 2600;</code>
     */
    public static final int RESOURCE_TYPE_TCP_VALUE = 2600;
    /**
     * <code>RESOURCE_TYPE_REDIS = 1600;</code>
     */
    public static final int RESOURCE_TYPE_REDIS_VALUE = 1600;
    /**
     * <code>RESOURCE_TYPE_REDIS_CLUSTER = 1602;</code>
     */
    public static final int RESOURCE_TYPE_REDIS_CLUSTER_VALUE = 1602;
    /**
     * <code>RESOURCE_TYPE_REDSHIFT = 1304;</code>
     */
    public static final int RESOURCE_TYPE_REDSHIFT_VALUE = 1304;
    /**
     * <code>RESOURCE_TYPE_REDSHIFT_IAM = 1312;</code>
     */
    public static final int RESOURCE_TYPE_REDSHIFT_IAM_VALUE = 1312;
    /**
     * <code>RESOURCE_TYPE_REDSHIFT_SERVERLESS_IAM = 1311;</code>
     */
    public static final int RESOURCE_TYPE_REDSHIFT_SERVERLESS_IAM_VALUE = 1311;
    /**
     * <code>RESOURCE_TYPE_SQL_SERVER = 1800;</code>
     */
    public static final int RESOURCE_TYPE_SQL_SERVER_VALUE = 1800;
    /**
     * <code>RESOURCE_TYPE_SQL_SERVER_AZURE_AD = 1805;</code>
     */
    public static final int RESOURCE_TYPE_SQL_SERVER_AZURE_AD_VALUE = 1805;
    /**
     * <code>RESOURCE_TYPE_SQL_SERVER_KERBEROS = 1810;</code>
     */
    public static final int RESOURCE_TYPE_SQL_SERVER_KERBEROS_VALUE = 1810;
    /**
     * <code>RESOURCE_TYPE_SSH = 1900;</code>
     */
    public static final int RESOURCE_TYPE_SSH_VALUE = 1900;
    /**
     * <code>RESOURCE_TYPE_SSH_CERT = 1901;</code>
     */
    public static final int RESOURCE_TYPE_SSH_CERT_VALUE = 1901;
    /**
     * <code>RESOURCE_TYPE_SSH_CERT_USER_PROVISION = 1903;</code>
     */
    public static final int RESOURCE_TYPE_SSH_CERT_USER_PROVISION_VALUE = 1903;
    /**
     * <code>RESOURCE_TYPE_SSH_CUSTOMER_KEY = 1902;</code>
     */
    public static final int RESOURCE_TYPE_SSH_CUSTOMER_KEY_VALUE = 1902;
    /**
     * <code>RESOURCE_TYPE_SSH_PASSWORD = 1904;</code>
     */
    public static final int RESOURCE_TYPE_SSH_PASSWORD_VALUE = 1904;
    /**
     * <code>RESOURCE_TYPE_SALESFORCE = 3305;</code>
     */
    public static final int RESOURCE_TYPE_SALESFORCE_VALUE = 3305;
    /**
     * <code>RESOURCE_TYPE_SINGLE_STORE = 1105;</code>
     */
    public static final int RESOURCE_TYPE_SINGLE_STORE_VALUE = 1105;
    /**
     * <code>RESOURCE_TYPE_SNOWFLAKE = 1700;</code>
     */
    public static final int RESOURCE_TYPE_SNOWFLAKE_VALUE = 1700;
    /**
     * <code>RESOURCE_TYPE_SNOWSIGHT = 1701;</code>
     */
    public static final int RESOURCE_TYPE_SNOWSIGHT_VALUE = 1701;
    /**
     * <code>RESOURCE_TYPE_SYBASE_ASE = 2000;</code>
     */
    public static final int RESOURCE_TYPE_SYBASE_ASE_VALUE = 2000;
    /**
     * <code>RESOURCE_TYPE_SYBASE_IQ = 2001;</code>
     */
    public static final int RESOURCE_TYPE_SYBASE_IQ_VALUE = 2001;
    /**
     * <code>RESOURCE_TYPE_TERADATA = 2100;</code>
     */
    public static final int RESOURCE_TYPE_TERADATA_VALUE = 2100;
    /**
     * <code>RESOURCE_TYPE_TRINO = 1401;</code>
     */
    public static final int RESOURCE_TYPE_TRINO_VALUE = 1401;
    /**
     * <code>RESOURCE_TYPE_VERTICA = 4500;</code>
     */
    public static final int RESOURCE_TYPE_VERTICA_VALUE = 4500;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResourceType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ResourceType forNumber(int value) {
      switch (value) {
        case 0: return RESOURCE_TYPE_UNSPECIFIED;
        case 805: return RESOURCE_TYPE_AKS;
        case 806: return RESOURCE_TYPE_AKS_BASIC_AUTH;
        case 807: return RESOURCE_TYPE_AKS_SERVICE_ACCOUNT;
        case 810: return RESOURCE_TYPE_AKS_SERVICE_ACCOUNT_USER_IMPERSONATION;
        case 814: return RESOURCE_TYPE_AKS_USER_IMPERSONATION;
        case 2502: return RESOURCE_TYPE_AMAZON_MQAMQP;
        case 2300: return RESOURCE_TYPE_AWS;
        case 3000: return RESOURCE_TYPE_AWS_CONSOLE;
        case 3001: return RESOURCE_TYPE_AWS_CONSOLE_STATIC_KEY_PAIR;
        case 2301: return RESOURCE_TYPE_AWS_INSTANCE_PROFILE;
        case 4600: return RESOURCE_TYPE_AEROSPIKE;
        case 802: return RESOURCE_TYPE_AMAZON_EKS;
        case 809: return RESOURCE_TYPE_AMAZON_EKS_INSTANCE_PROFILE;
        case 813: return RESOURCE_TYPE_AMAZON_EKS_INSTANCE_PROFILE_USER_IMPERSONATION;
        case 818: return RESOURCE_TYPE_AMAZON_EKS_USER_IMPERSONATION;
        case 600: return RESOURCE_TYPE_AMAZON_ES;
        case 602: return RESOURCE_TYPE_AMAZON_ESIAM;
        case 2501: return RESOURCE_TYPE_AMAZON_MQAMQP_091;
        case 100: return RESOURCE_TYPE_ATHENA;
        case 3400: return RESOURCE_TYPE_ATHENA_IAM;
        case 1101: return RESOURCE_TYPE_AURORA_MY_SQL;
        case 1109: return RESOURCE_TYPE_AURORA_MY_SQLIAM;
        case 1301: return RESOURCE_TYPE_AURORA_POSTGRES;
        case 1309: return RESOURCE_TYPE_AURORA_POSTGRES_IAM;
        case 2800: return RESOURCE_TYPE_AZURE;
        case 2801: return RESOURCE_TYPE_AZURE_CERT;
        case 1107: return RESOURCE_TYPE_AZURE_MY_SQL;
        case 1110: return RESOURCE_TYPE_AZURE_MY_SQL_MANAGED_IDENTITY;
        case 1307: return RESOURCE_TYPE_AZURE_POSTGRES;
        case 1308: return RESOURCE_TYPE_AZURE_POSTGRES_MANAGED_IDENTITY;
        case 200: return RESOURCE_TYPE_BIGQUERY;
        case 300: return RESOURCE_TYPE_CASSANDRA;
        case 1305: return RESOURCE_TYPE_CITUS;
        case 5: return RESOURCE_TYPE_CLICK_HOUSE_HTTP;
        case 1108: return RESOURCE_TYPE_CLICK_HOUSE_MY_SQL;
        case 6: return RESOURCE_TYPE_CLICK_HOUSE_TCP;
        case 1102: return RESOURCE_TYPE_CLUSTRIX;
        case 1303: return RESOURCE_TYPE_COCKROACH;
        case 3201: return RESOURCE_TYPE_COUCHBASE_DATABASE;
        case 3200: return RESOURCE_TYPE_COUCHBASE_WEB_UI;
        case 2400: return RESOURCE_TYPE_DB_2_I;
        case 2200: return RESOURCE_TYPE_DB_2_LUW;
        case 1052: return RESOURCE_TYPE_DOCUMENT_DB_HOST;
        case 1055: return RESOURCE_TYPE_DOCUMENT_DB_HOST_IAM;
        case 1053: return RESOURCE_TYPE_DOCUMENT_DB_REPLICA_SET;
        case 1056: return RESOURCE_TYPE_DOCUMENT_DB_REPLICA_SET_IAM;
        case 400: return RESOURCE_TYPE_DRUID;
        case 500: return RESOURCE_TYPE_DYNAMO_DB;
        case 501: return RESOURCE_TYPE_DYNAMO_DBIAM;
        case 601: return RESOURCE_TYPE_ELASTIC;
        case 1601: return RESOURCE_TYPE_ELASTI_CACHE_REDIS;
        case 1603: return RESOURCE_TYPE_ELASTI_CACHE_REDIS_IAM;
        case 2803: return RESOURCE_TYPE_ENTRA_ID;
        case 2700: return RESOURCE_TYPE_GCP;
        case 3300: return RESOURCE_TYPE_GCP_CONSOLE;
        case 2701: return RESOURCE_TYPE_GCPWIF;
        case 3301: return RESOURCE_TYPE_GIT_HUB;
        case 3302: return RESOURCE_TYPE_GOOGLE_ADMIN;
        case 803: return RESOURCE_TYPE_GOOGLE_GKE;
        case 816: return RESOURCE_TYPE_GOOGLE_GKE_USER_IMPERSONATION;
        case 4800: return RESOURCE_TYPE_GOOGLE_SPANNER;
        case 1302: return RESOURCE_TYPE_GREENPLUM;
        case 702: return RESOURCE_TYPE_HTTP_AUTH;
        case 700: return RESOURCE_TYPE_HTTP_BASIC;
        case 701: return RESOURCE_TYPE_HTTP_NO_AUTH;
        case 800: return RESOURCE_TYPE_KUBERNETES;
        case 801: return RESOURCE_TYPE_KUBERNETES_BASIC_AUTH;
        case 819: return RESOURCE_TYPE_KUBERNETES_POD_IDENTITY;
        case 804: return RESOURCE_TYPE_KUBERNETES_SERVICE_ACCOUNT;
        case 808: return RESOURCE_TYPE_KUBERNETES_SERVICE_ACCOUNT_USER_IMPERSONATION;
        case 812: return RESOURCE_TYPE_KUBERNETES_USER_IMPERSONATION;
        case 4700: return RESOURCE_TYPE_MCP;
        case 4701: return RESOURCE_TYPE_MCPDCR;
        case 1106: return RESOURCE_TYPE_MTLS_MY_SQL;
        case 1306: return RESOURCE_TYPE_MTLS_POSTGRES;
        case 1103: return RESOURCE_TYPE_MARIA;
        case 900: return RESOURCE_TYPE_MEMCACHED;
        case 1104: return RESOURCE_TYPE_MEM_SQL;
        case 3303: return RESOURCE_TYPE_MICROSOFT_365;
        case 1002: return RESOURCE_TYPE_MONGO_DB_HOST;
        case 1000: return RESOURCE_TYPE_MONGO_DB;
        case 1001: return RESOURCE_TYPE_MONGO_DB_LEGACY_REPLICA_SET;
        case 1003: return RESOURCE_TYPE_MONGO_DB_REPLICA_SET;
        case 1054: return RESOURCE_TYPE_MONGO_DB_SHARDED_CLUSTER;
        case 1100: return RESOURCE_TYPE_MY_SQL;
        case 2250: return RESOURCE_TYPE_NEPTUNE;
        case 2201: return RESOURCE_TYPE_NEPTUNE_IAM;
        case 3304: return RESOURCE_TYPE_OKTA_ADMIN;
        case 3500: return RESOURCE_TYPE_OKTA_GROUPS;
        case 1200: return RESOURCE_TYPE_ORACLE;
        case 1201: return RESOURCE_TYPE_ORACLE_NNE;
        case 1300: return RESOURCE_TYPE_POSTGRES;
        case 1400: return RESOURCE_TYPE_PRESTO;
        case 1500: return RESOURCE_TYPE_RDP;
        case 1501: return RESOURCE_TYPE_RDP_CERT;
        case 1310: return RESOURCE_TYPE_RDS_POSTGRES_IAM;
        case 2500: return RESOURCE_TYPE_RABBIT_MQAMQP_091;
        case 2600: return RESOURCE_TYPE_TCP;
        case 1600: return RESOURCE_TYPE_REDIS;
        case 1602: return RESOURCE_TYPE_REDIS_CLUSTER;
        case 1304: return RESOURCE_TYPE_REDSHIFT;
        case 1312: return RESOURCE_TYPE_REDSHIFT_IAM;
        case 1311: return RESOURCE_TYPE_REDSHIFT_SERVERLESS_IAM;
        case 1800: return RESOURCE_TYPE_SQL_SERVER;
        case 1805: return RESOURCE_TYPE_SQL_SERVER_AZURE_AD;
        case 1810: return RESOURCE_TYPE_SQL_SERVER_KERBEROS;
        case 1900: return RESOURCE_TYPE_SSH;
        case 1901: return RESOURCE_TYPE_SSH_CERT;
        case 1903: return RESOURCE_TYPE_SSH_CERT_USER_PROVISION;
        case 1902: return RESOURCE_TYPE_SSH_CUSTOMER_KEY;
        case 1904: return RESOURCE_TYPE_SSH_PASSWORD;
        case 3305: return RESOURCE_TYPE_SALESFORCE;
        case 1105: return RESOURCE_TYPE_SINGLE_STORE;
        case 1700: return RESOURCE_TYPE_SNOWFLAKE;
        case 1701: return RESOURCE_TYPE_SNOWSIGHT;
        case 2000: return RESOURCE_TYPE_SYBASE_ASE;
        case 2001: return RESOURCE_TYPE_SYBASE_IQ;
        case 2100: return RESOURCE_TYPE_TERADATA;
        case 1401: return RESOURCE_TYPE_TRINO;
        case 4500: return RESOURCE_TYPE_VERTICA;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ResourceType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ResourceType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ResourceType>() {
            public ResourceType findValueByNumber(int number) {
              return ResourceType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.strongdm.api.plumbing.ResourceTypePlumbing.getDescriptor().getEnumTypes().get(0);
    }

    private static final ResourceType[] VALUES = values();

    public static ResourceType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ResourceType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:v1.ResourceType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023resourcetypes.proto\022\002v1*\337 \n\014ResourceTy" +
      "pe\022\035\n\031RESOURCE_TYPE_UNSPECIFIED\020\000\022\026\n\021RES" +
      "OURCE_TYPE_AKS\020\245\006\022!\n\034RESOURCE_TYPE_AKS_B" +
      "ASIC_AUTH\020\246\006\022&\n!RESOURCE_TYPE_AKS_SERVIC" +
      "E_ACCOUNT\020\247\006\0229\n4RESOURCE_TYPE_AKS_SERVIC" +
      "E_ACCOUNT_USER_IMPERSONATION\020\252\006\022)\n$RESOU" +
      "RCE_TYPE_AKS_USER_IMPERSONATION\020\256\006\022 \n\033RE" +
      "SOURCE_TYPE_AMAZON_MQAMQP\020\306\023\022\026\n\021RESOURCE" +
      "_TYPE_AWS\020\374\021\022\036\n\031RESOURCE_TYPE_AWS_CONSOL" +
      "E\020\270\027\022.\n)RESOURCE_TYPE_AWS_CONSOLE_STATIC" +
      "_KEY_PAIR\020\271\027\022\'\n\"RESOURCE_TYPE_AWS_INSTAN" +
      "CE_PROFILE\020\375\021\022\034\n\027RESOURCE_TYPE_AEROSPIKE" +
      "\020\370#\022\035\n\030RESOURCE_TYPE_AMAZON_EKS\020\242\006\022.\n)RE" +
      "SOURCE_TYPE_AMAZON_EKS_INSTANCE_PROFILE\020" +
      "\251\006\022A\n<RESOURCE_TYPE_AMAZON_EKS_INSTANCE_" +
      "PROFILE_USER_IMPERSONATION\020\255\006\0220\n+RESOURC" +
      "E_TYPE_AMAZON_EKS_USER_IMPERSONATION\020\262\006\022" +
      "\034\n\027RESOURCE_TYPE_AMAZON_ES\020\330\004\022\037\n\032RESOURC" +
      "E_TYPE_AMAZON_ESIAM\020\332\004\022$\n\037RESOURCE_TYPE_" +
      "AMAZON_MQAMQP_091\020\305\023\022\030\n\024RESOURCE_TYPE_AT" +
      "HENA\020d\022\035\n\030RESOURCE_TYPE_ATHENA_IAM\020\310\032\022 \n" +
      "\033RESOURCE_TYPE_AURORA_MY_SQL\020\315\010\022#\n\036RESOU" +
      "RCE_TYPE_AURORA_MY_SQLIAM\020\325\010\022\"\n\035RESOURCE" +
      "_TYPE_AURORA_POSTGRES\020\225\n\022&\n!RESOURCE_TYP" +
      "E_AURORA_POSTGRES_IAM\020\235\n\022\030\n\023RESOURCE_TYP" +
      "E_AZURE\020\360\025\022\035\n\030RESOURCE_TYPE_AZURE_CERT\020\361" +
      "\025\022\037\n\032RESOURCE_TYPE_AZURE_MY_SQL\020\323\010\0220\n+RE" +
      "SOURCE_TYPE_AZURE_MY_SQL_MANAGED_IDENTIT" +
      "Y\020\326\010\022!\n\034RESOURCE_TYPE_AZURE_POSTGRES\020\233\n\022" +
      "2\n-RESOURCE_TYPE_AZURE_POSTGRES_MANAGED_" +
      "IDENTITY\020\234\n\022\033\n\026RESOURCE_TYPE_BIGQUERY\020\310\001" +
      "\022\034\n\027RESOURCE_TYPE_CASSANDRA\020\254\002\022\030\n\023RESOUR" +
      "CE_TYPE_CITUS\020\231\n\022\"\n\036RESOURCE_TYPE_CLICK_" +
      "HOUSE_HTTP\020\005\022%\n RESOURCE_TYPE_CLICK_HOUS" +
      "E_MY_SQL\020\324\010\022!\n\035RESOURCE_TYPE_CLICK_HOUSE" +
      "_TCP\020\006\022\033\n\026RESOURCE_TYPE_CLUSTRIX\020\316\010\022\034\n\027R" +
      "ESOURCE_TYPE_COCKROACH\020\227\n\022%\n RESOURCE_TY" +
      "PE_COUCHBASE_DATABASE\020\201\031\022#\n\036RESOURCE_TYP" +
      "E_COUCHBASE_WEB_UI\020\200\031\022\031\n\024RESOURCE_TYPE_D" +
      "B_2_I\020\340\022\022\033\n\026RESOURCE_TYPE_DB_2_LUW\020\230\021\022#\n" +
      "\036RESOURCE_TYPE_DOCUMENT_DB_HOST\020\234\010\022\'\n\"RE" +
      "SOURCE_TYPE_DOCUMENT_DB_HOST_IAM\020\237\010\022*\n%R" +
      "ESOURCE_TYPE_DOCUMENT_DB_REPLICA_SET\020\235\010\022" +
      ".\n)RESOURCE_TYPE_DOCUMENT_DB_REPLICA_SET" +
      "_IAM\020\240\010\022\030\n\023RESOURCE_TYPE_DRUID\020\220\003\022\034\n\027RES" +
      "OURCE_TYPE_DYNAMO_DB\020\364\003\022\037\n\032RESOURCE_TYPE" +
      "_DYNAMO_DBIAM\020\365\003\022\032\n\025RESOURCE_TYPE_ELASTI" +
      "C\020\331\004\022%\n RESOURCE_TYPE_ELASTI_CACHE_REDIS" +
      "\020\301\014\022)\n$RESOURCE_TYPE_ELASTI_CACHE_REDIS_" +
      "IAM\020\303\014\022\033\n\026RESOURCE_TYPE_ENTRA_ID\020\363\025\022\026\n\021R" +
      "ESOURCE_TYPE_GCP\020\214\025\022\036\n\031RESOURCE_TYPE_GCP" +
      "_CONSOLE\020\344\031\022\031\n\024RESOURCE_TYPE_GCPWIF\020\215\025\022\032" +
      "\n\025RESOURCE_TYPE_GIT_HUB\020\345\031\022\037\n\032RESOURCE_T" +
      "YPE_GOOGLE_ADMIN\020\346\031\022\035\n\030RESOURCE_TYPE_GOO" +
      "GLE_GKE\020\243\006\0220\n+RESOURCE_TYPE_GOOGLE_GKE_U" +
      "SER_IMPERSONATION\020\260\006\022!\n\034RESOURCE_TYPE_GO" +
      "OGLE_SPANNER\020\300%\022\034\n\027RESOURCE_TYPE_GREENPL" +
      "UM\020\226\n\022\034\n\027RESOURCE_TYPE_HTTP_AUTH\020\276\005\022\035\n\030R" +
      "ESOURCE_TYPE_HTTP_BASIC\020\274\005\022\037\n\032RESOURCE_T" +
      "YPE_HTTP_NO_AUTH\020\275\005\022\035\n\030RESOURCE_TYPE_KUB" +
      "ERNETES\020\240\006\022(\n#RESOURCE_TYPE_KUBERNETES_B" +
      "ASIC_AUTH\020\241\006\022*\n%RESOURCE_TYPE_KUBERNETES" +
      "_POD_IDENTITY\020\263\006\022-\n(RESOURCE_TYPE_KUBERN" +
      "ETES_SERVICE_ACCOUNT\020\244\006\022@\n;RESOURCE_TYPE" +
      "_KUBERNETES_SERVICE_ACCOUNT_USER_IMPERSO" +
      "NATION\020\250\006\0220\n+RESOURCE_TYPE_KUBERNETES_US" +
      "ER_IMPERSONATION\020\254\006\022\026\n\021RESOURCE_TYPE_MCP" +
      "\020\334$\022\031\n\024RESOURCE_TYPE_MCPDCR\020\335$\022\036\n\031RESOUR" +
      "CE_TYPE_MTLS_MY_SQL\020\322\010\022 \n\033RESOURCE_TYPE_" +
      "MTLS_POSTGRES\020\232\n\022\030\n\023RESOURCE_TYPE_MARIA\020" +
      "\317\010\022\034\n\027RESOURCE_TYPE_MEMCACHED\020\204\007\022\032\n\025RESO" +
      "URCE_TYPE_MEM_SQL\020\320\010\022 \n\033RESOURCE_TYPE_MI" +
      "CROSOFT_365\020\347\031\022 \n\033RESOURCE_TYPE_MONGO_DB" +
      "_HOST\020\352\007\022\033\n\026RESOURCE_TYPE_MONGO_DB\020\350\007\022.\n" +
      ")RESOURCE_TYPE_MONGO_DB_LEGACY_REPLICA_S" +
      "ET\020\351\007\022\'\n\"RESOURCE_TYPE_MONGO_DB_REPLICA_" +
      "SET\020\353\007\022+\n&RESOURCE_TYPE_MONGO_DB_SHARDED" +
      "_CLUSTER\020\236\010\022\031\n\024RESOURCE_TYPE_MY_SQL\020\314\010\022\032" +
      "\n\025RESOURCE_TYPE_NEPTUNE\020\312\021\022\036\n\031RESOURCE_T" +
      "YPE_NEPTUNE_IAM\020\231\021\022\035\n\030RESOURCE_TYPE_OKTA" +
      "_ADMIN\020\350\031\022\036\n\031RESOURCE_TYPE_OKTA_GROUPS\020\254" +
      "\033\022\031\n\024RESOURCE_TYPE_ORACLE\020\260\t\022\035\n\030RESOURCE" +
      "_TYPE_ORACLE_NNE\020\261\t\022\033\n\026RESOURCE_TYPE_POS" +
      "TGRES\020\224\n\022\031\n\024RESOURCE_TYPE_PRESTO\020\370\n\022\026\n\021R" +
      "ESOURCE_TYPE_RDP\020\334\013\022\033\n\026RESOURCE_TYPE_RDP" +
      "_CERT\020\335\013\022#\n\036RESOURCE_TYPE_RDS_POSTGRES_I" +
      "AM\020\236\n\022$\n\037RESOURCE_TYPE_RABBIT_MQAMQP_091" +
      "\020\304\023\022\026\n\021RESOURCE_TYPE_TCP\020\250\024\022\030\n\023RESOURCE_" +
      "TYPE_REDIS\020\300\014\022 \n\033RESOURCE_TYPE_REDIS_CLU" +
      "STER\020\302\014\022\033\n\026RESOURCE_TYPE_REDSHIFT\020\230\n\022\037\n\032" +
      "RESOURCE_TYPE_REDSHIFT_IAM\020\240\n\022*\n%RESOURC" +
      "E_TYPE_REDSHIFT_SERVERLESS_IAM\020\237\n\022\035\n\030RES" +
      "OURCE_TYPE_SQL_SERVER\020\210\016\022&\n!RESOURCE_TYP" +
      "E_SQL_SERVER_AZURE_AD\020\215\016\022&\n!RESOURCE_TYP" +
      "E_SQL_SERVER_KERBEROS\020\222\016\022\026\n\021RESOURCE_TYP" +
      "E_SSH\020\354\016\022\033\n\026RESOURCE_TYPE_SSH_CERT\020\355\016\022*\n" +
      "%RESOURCE_TYPE_SSH_CERT_USER_PROVISION\020\357" +
      "\016\022#\n\036RESOURCE_TYPE_SSH_CUSTOMER_KEY\020\356\016\022\037" +
      "\n\032RESOURCE_TYPE_SSH_PASSWORD\020\360\016\022\035\n\030RESOU" +
      "RCE_TYPE_SALESFORCE\020\351\031\022\037\n\032RESOURCE_TYPE_" +
      "SINGLE_STORE\020\321\010\022\034\n\027RESOURCE_TYPE_SNOWFLA" +
      "KE\020\244\r\022\034\n\027RESOURCE_TYPE_SNOWSIGHT\020\245\r\022\035\n\030R" +
      "ESOURCE_TYPE_SYBASE_ASE\020\320\017\022\034\n\027RESOURCE_T" +
      "YPE_SYBASE_IQ\020\321\017\022\033\n\026RESOURCE_TYPE_TERADA" +
      "TA\020\264\020\022\030\n\023RESOURCE_TYPE_TRINO\020\371\n\022\032\n\025RESOU" +
      "RCE_TYPE_VERTICA\020\224#Bm\n\031com.strongdm.api." +
      "plumbingB\024ResourceTypePlumbingZ:github.c" +
      "om/strongdm/web/pkg/api/v1/generated/go_" +
      "private/v1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
