// Copyright 2020 StrongDM Inc
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// 

// This file was generated by protogen. DO NOT EDIT.

package com.strongdm.api.v1;

import java.util.ArrayList;
import java.util.List;
import java.util.Collection;
import java.util.Date;

// AccountAttachmentGetResponse returns a requested AccountAttachment.
public class AccountAttachmentGetResponse
    {
    private GetResponseMetadata meta;
    // Reserved for future use.
    public GetResponseMetadata getMeta() {
        return this.meta;
    }
    // Reserved for future use.
    public void setMeta(GetResponseMetadata in) {
        this.meta = in;
    }
    private AccountAttachment accountAttachment;
    // The requested AccountAttachment.
    public AccountAttachment getAccountAttachment() {
        return this.accountAttachment;
    }
    // The requested AccountAttachment.
    public void setAccountAttachment(AccountAttachment in) {
        this.accountAttachment = in;
    }
    private RateLimitMetadata rateLimit;
    // Rate limit information.
    public RateLimitMetadata getRateLimit() {
        return this.rateLimit;
    }
    // Rate limit information.
    public void setRateLimit(RateLimitMetadata in) {
        this.rateLimit = in;
    }
}
