// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// This file was generated by protogen. DO NOT EDIT.

package com.strongdm.api.v1;

public class Kubernetes implements Resource {
  private String id;
  // Unique identifier of the Resource.
  public String getId() {
    return this.id;
  }
  // Unique identifier of the Resource.
  public void setId(String in) {
    this.id = in;
  }

  private String name;
  // Unique human-readable name of the Resource.
  public String getName() {
    return this.name;
  }
  // Unique human-readable name of the Resource.
  public void setName(String in) {
    this.name = in;
  }

  private boolean healthy;
  // True if the datasource is reachable and the credentials are valid.
  public boolean getHealthy() {
    return this.healthy;
  }
  // True if the datasource is reachable and the credentials are valid.
  public void setHealthy(boolean in) {
    this.healthy = in;
  }

  private java.util.Map<String, String> tags;
  // Tags is a map of key, value pairs.
  public java.util.Map<String, String> getTags() {
    java.util.Map<String, String> m = new java.util.HashMap<String, String>();
    if (this.tags != null) {
      m.putAll(this.tags);
    }
    return m;
  }
  // Tags is a map of key, value pairs.
  public void setTags(java.util.Map<String, String> in) {
    if (in == null) {
      this.tags = null;
      return;
    }
    this.tags = new java.util.HashMap<String, String>();
    this.tags.putAll(in);
  }

  private String hostname;

  public String getHostname() {
    return this.hostname;
  }

  public void setHostname(String in) {
    this.hostname = in;
  }

  private int port;

  public int getPort() {
    return this.port;
  }

  public void setPort(int in) {
    this.port = in;
  }

  private String certificateAuthority;

  public String getCertificateAuthority() {
    return this.certificateAuthority;
  }

  public void setCertificateAuthority(String in) {
    this.certificateAuthority = in;
  }

  private String certificateAuthorityFilename;

  public String getCertificateAuthorityFilename() {
    return this.certificateAuthorityFilename;
  }

  public void setCertificateAuthorityFilename(String in) {
    this.certificateAuthorityFilename = in;
  }

  private String clientCertificate;

  public String getClientCertificate() {
    return this.clientCertificate;
  }

  public void setClientCertificate(String in) {
    this.clientCertificate = in;
  }

  private String clientCertificateFilename;

  public String getClientCertificateFilename() {
    return this.clientCertificateFilename;
  }

  public void setClientCertificateFilename(String in) {
    this.clientCertificateFilename = in;
  }

  private String clientKey;

  public String getClientKey() {
    return this.clientKey;
  }

  public void setClientKey(String in) {
    this.clientKey = in;
  }

  private String clientKeyFilename;

  public String getClientKeyFilename() {
    return this.clientKeyFilename;
  }

  public void setClientKeyFilename(String in) {
    this.clientKeyFilename = in;
  }
}
