// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// This file was generated by protogen. DO NOT EDIT.

package com.strongdm.api.v1;

public class KubernetesBasicAuth implements Resource {
  private String id;
  // Unique identifier of the Resource.
  public String getId() {
    return this.id;
  }
  // Unique identifier of the Resource.
  public KubernetesBasicAuth setId(String in) {
    this.id = in;
    return this;
  }

  private String name;
  // Unique human-readable name of the Resource.
  public String getName() {
    return this.name;
  }
  // Unique human-readable name of the Resource.
  public KubernetesBasicAuth setName(String in) {
    this.name = in;
    return this;
  }

  private boolean healthy;
  // True if the datasource is reachable and the credentials are valid.
  public boolean getHealthy() {
    return this.healthy;
  }
  // True if the datasource is reachable and the credentials are valid.
  public KubernetesBasicAuth setHealthy(boolean in) {
    this.healthy = in;
    return this;
  }

  private java.util.Map<String, String> tags;
  // Tags is a map of key, value pairs.
  public java.util.Map<String, String> getTags() {
    return this.tags;
  }
  // Tags is a map of key, value pairs.
  public KubernetesBasicAuth setTags(java.util.Map<String, String> in) {
    this.tags = in;
    return this;
  }

  private String hostname;

  public String getHostname() {
    return this.hostname;
  }

  public KubernetesBasicAuth setHostname(String in) {
    this.hostname = in;
    return this;
  }

  private int port;

  public int getPort() {
    return this.port;
  }

  public KubernetesBasicAuth setPort(int in) {
    this.port = in;
    return this;
  }

  private String username;

  public String getUsername() {
    return this.username;
  }

  public KubernetesBasicAuth setUsername(String in) {
    this.username = in;
    return this;
  }

  private String password;

  public String getPassword() {
    return this.password;
  }

  public KubernetesBasicAuth setPassword(String in) {
    this.password = in;
    return this;
  }
}
