// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// This file was generated by protogen. DO NOT EDIT.

package com.strongdm.api.v1;

/** NodeCreateResponse reports how the Nodes were created in the system. */
public class NodeCreateResponse {
  private CreateResponseMetadata meta;
  /** Reserved for future use. */
  public CreateResponseMetadata getMeta() {
    return this.meta;
  }
  /** Reserved for future use. */
  public void setMeta(CreateResponseMetadata in) {
    this.meta = in;
  }

  private Node node;
  /** The created Node. */
  public Node getNode() {
    return this.node;
  }
  /** The created Node. */
  public void setNode(Node in) {
    this.node = in;
  }

  private RateLimitMetadata rateLimit;
  /** Rate limit information. */
  public RateLimitMetadata getRateLimit() {
    return this.rateLimit;
  }
  /** Rate limit information. */
  public void setRateLimit(RateLimitMetadata in) {
    this.rateLimit = in;
  }

  private String token;
  /**
   * The auth token generated for the Node. The Node will use this token to authenticate with the
   * strongDM API.
   */
  public String getToken() {
    return this.token;
  }
  /**
   * The auth token generated for the Node. The Node will use this token to authenticate with the
   * strongDM API.
   */
  public void setToken(String in) {
    this.token = in;
  }
}
