// Copyright 2020 StrongDM Inc
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// 

// This file was generated by protogen. DO NOT EDIT.

package com.strongdm.api.v1;

import java.util.ArrayList;
import java.util.List;
import java.util.Collection;
import java.util.Date;

// A RoleAttachment assigns a role to a composite role.
public class RoleAttachment
    {
    private String id;
    // Unique identifier of the RoleAttachment.
    public String getId() {
        return this.id;
    }
    // Unique identifier of the RoleAttachment.
    public void setId(String in) {
        this.id = in;
    }
    private String compositeRoleId;
    // The id of the composite role of this RoleAttachment.
    public String getCompositeRoleId() {
        return this.compositeRoleId;
    }
    // The id of the composite role of this RoleAttachment.
    public void setCompositeRoleId(String in) {
        this.compositeRoleId = in;
    }
    private String attachedRoleId;
    // The id of the attached role of this RoleAttachment.
    public String getAttachedRoleId() {
        return this.attachedRoleId;
    }
    // The id of the attached role of this RoleAttachment.
    public void setAttachedRoleId(String in) {
        this.attachedRoleId = in;
    }
}
