// Copyright 2020 StrongDM Inc
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// 

// This file was generated by protogen. DO NOT EDIT.

package com.strongdm.api.v1.plumbing;

import java.util.List;
import java.util.ArrayList;

public class PageResult<T> {
    private final List<T> page;
    public List<T> getPage() {
        return this.page;
    }

    private final boolean hasNextPage;
    public boolean hasNextPage() {
        return this.hasNextPage;
    }

    public PageResult(List<T> page, boolean hasNextPage) {
        this.page = page;
        this.hasNextPage = hasNextPage;
    }
}
