// Copyright 2020 StrongDM Inc
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// 
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tags.proto

package com.strongdm.api.v1.plumbing;

public final class TagsPlumbing {
  private TagsPlumbing() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TagsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:v1.Tags)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .v1.Tags.Pair pairs = 1;</code>
     */
    java.util.List<com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair> 
        getPairsList();
    /**
     * <code>repeated .v1.Tags.Pair pairs = 1;</code>
     */
    com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair getPairs(int index);
    /**
     * <code>repeated .v1.Tags.Pair pairs = 1;</code>
     */
    int getPairsCount();
    /**
     * <code>repeated .v1.Tags.Pair pairs = 1;</code>
     */
    java.util.List<? extends com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.PairOrBuilder> 
        getPairsOrBuilderList();
    /**
     * <code>repeated .v1.Tags.Pair pairs = 1;</code>
     */
    com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.PairOrBuilder getPairsOrBuilder(
        int index);
  }
  /**
   * <pre>
   * Tags defines a custom message that will translate from a slice of
   * Pairs into a map[] in each supported language.  See options.proto for
   * documentation on the custom message options.
   * </pre>
   *
   * Protobuf type {@code v1.Tags}
   */
  public static final class Tags extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:v1.Tags)
      TagsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Tags.newBuilder() to construct.
    private Tags(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Tags() {
      pairs_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Tags();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Tags(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                pairs_ = new java.util.ArrayList<com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair>();
                mutable_bitField0_ |= 0x00000001;
              }
              pairs_.add(
                  input.readMessage(com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          pairs_ = java.util.Collections.unmodifiableList(pairs_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.strongdm.api.v1.plumbing.TagsPlumbing.internal_static_v1_Tags_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.strongdm.api.v1.plumbing.TagsPlumbing.internal_static_v1_Tags_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.class, com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Builder.class);
    }

    public interface PairOrBuilder extends
        // @@protoc_insertion_point(interface_extends:v1.Tags.Pair)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      java.lang.String getName();
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      com.google.protobuf.ByteString
          getNameBytes();

      /**
       * <code>string value = 2;</code>
       * @return The value.
       */
      java.lang.String getValue();
      /**
       * <code>string value = 2;</code>
       * @return The bytes for value.
       */
      com.google.protobuf.ByteString
          getValueBytes();
    }
    /**
     * Protobuf type {@code v1.Tags.Pair}
     */
    public static final class Pair extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:v1.Tags.Pair)
        PairOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Pair.newBuilder() to construct.
      private Pair(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Pair() {
        name_ = "";
        value_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Pair();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Pair(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                value_ = s;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.strongdm.api.v1.plumbing.TagsPlumbing.internal_static_v1_Tags_Pair_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.strongdm.api.v1.plumbing.TagsPlumbing.internal_static_v1_Tags_Pair_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair.class, com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair.Builder.class);
      }

      public static final int NAME_FIELD_NUMBER = 1;
      private volatile java.lang.Object name_;
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      @java.lang.Override
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int VALUE_FIELD_NUMBER = 2;
      private volatile java.lang.Object value_;
      /**
       * <code>string value = 2;</code>
       * @return The value.
       */
      @java.lang.Override
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        }
      }
      /**
       * <code>string value = 2;</code>
       * @return The bytes for value.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair)) {
          return super.equals(obj);
        }
        com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair other = (com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair) obj;

        if (!getName()
            .equals(other.getName())) return false;
        if (!getValue()
            .equals(other.getValue())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code v1.Tags.Pair}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:v1.Tags.Pair)
          com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.PairOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.strongdm.api.v1.plumbing.TagsPlumbing.internal_static_v1_Tags_Pair_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.strongdm.api.v1.plumbing.TagsPlumbing.internal_static_v1_Tags_Pair_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair.class, com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair.Builder.class);
        }

        // Construct using com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          name_ = "";

          value_ = "";

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.strongdm.api.v1.plumbing.TagsPlumbing.internal_static_v1_Tags_Pair_descriptor;
        }

        @java.lang.Override
        public com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair getDefaultInstanceForType() {
          return com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair.getDefaultInstance();
        }

        @java.lang.Override
        public com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair build() {
          com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair buildPartial() {
          com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair result = new com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair(this);
          result.name_ = name_;
          result.value_ = value_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair) {
            return mergeFrom((com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair other) {
          if (other == com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair.getDefaultInstance()) return this;
          if (!other.getName().isEmpty()) {
            name_ = other.name_;
            onChanged();
          }
          if (!other.getValue().isEmpty()) {
            value_ = other.value_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object name_ = "";
        /**
         * <code>string name = 1;</code>
         * @return The name.
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string name = 1;</code>
         * @return The bytes for name.
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string name = 1;</code>
         * @param value The name to set.
         * @return This builder for chaining.
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string name = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearName() {
          
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>string name = 1;</code>
         * @param value The bytes for name to set.
         * @return This builder for chaining.
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          name_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object value_ = "";
        /**
         * <code>string value = 2;</code>
         * @return The value.
         */
        public java.lang.String getValue() {
          java.lang.Object ref = value_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            value_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string value = 2;</code>
         * @return The bytes for value.
         */
        public com.google.protobuf.ByteString
            getValueBytes() {
          java.lang.Object ref = value_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            value_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string value = 2;</code>
         * @param value The value to set.
         * @return This builder for chaining.
         */
        public Builder setValue(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string value = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearValue() {
          
          value_ = getDefaultInstance().getValue();
          onChanged();
          return this;
        }
        /**
         * <code>string value = 2;</code>
         * @param value The bytes for value to set.
         * @return This builder for chaining.
         */
        public Builder setValueBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          value_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:v1.Tags.Pair)
      }

      // @@protoc_insertion_point(class_scope:v1.Tags.Pair)
      private static final com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair();
      }

      public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Pair>
          PARSER = new com.google.protobuf.AbstractParser<Pair>() {
        @java.lang.Override
        public Pair parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Pair(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Pair> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Pair> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int PAIRS_FIELD_NUMBER = 1;
    private java.util.List<com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair> pairs_;
    /**
     * <code>repeated .v1.Tags.Pair pairs = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair> getPairsList() {
      return pairs_;
    }
    /**
     * <code>repeated .v1.Tags.Pair pairs = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.PairOrBuilder> 
        getPairsOrBuilderList() {
      return pairs_;
    }
    /**
     * <code>repeated .v1.Tags.Pair pairs = 1;</code>
     */
    @java.lang.Override
    public int getPairsCount() {
      return pairs_.size();
    }
    /**
     * <code>repeated .v1.Tags.Pair pairs = 1;</code>
     */
    @java.lang.Override
    public com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair getPairs(int index) {
      return pairs_.get(index);
    }
    /**
     * <code>repeated .v1.Tags.Pair pairs = 1;</code>
     */
    @java.lang.Override
    public com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.PairOrBuilder getPairsOrBuilder(
        int index) {
      return pairs_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < pairs_.size(); i++) {
        output.writeMessage(1, pairs_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < pairs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, pairs_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.strongdm.api.v1.plumbing.TagsPlumbing.Tags)) {
        return super.equals(obj);
      }
      com.strongdm.api.v1.plumbing.TagsPlumbing.Tags other = (com.strongdm.api.v1.plumbing.TagsPlumbing.Tags) obj;

      if (!getPairsList()
          .equals(other.getPairsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPairsCount() > 0) {
        hash = (37 * hash) + PAIRS_FIELD_NUMBER;
        hash = (53 * hash) + getPairsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tags parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tags parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tags parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tags parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tags parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tags parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tags parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tags parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tags parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tags parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tags parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tags parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.strongdm.api.v1.plumbing.TagsPlumbing.Tags prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Tags defines a custom message that will translate from a slice of
     * Pairs into a map[] in each supported language.  See options.proto for
     * documentation on the custom message options.
     * </pre>
     *
     * Protobuf type {@code v1.Tags}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:v1.Tags)
        com.strongdm.api.v1.plumbing.TagsPlumbing.TagsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.strongdm.api.v1.plumbing.TagsPlumbing.internal_static_v1_Tags_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.strongdm.api.v1.plumbing.TagsPlumbing.internal_static_v1_Tags_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.class, com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Builder.class);
      }

      // Construct using com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPairsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (pairsBuilder_ == null) {
          pairs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          pairsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.strongdm.api.v1.plumbing.TagsPlumbing.internal_static_v1_Tags_descriptor;
      }

      @java.lang.Override
      public com.strongdm.api.v1.plumbing.TagsPlumbing.Tags getDefaultInstanceForType() {
        return com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.getDefaultInstance();
      }

      @java.lang.Override
      public com.strongdm.api.v1.plumbing.TagsPlumbing.Tags build() {
        com.strongdm.api.v1.plumbing.TagsPlumbing.Tags result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.strongdm.api.v1.plumbing.TagsPlumbing.Tags buildPartial() {
        com.strongdm.api.v1.plumbing.TagsPlumbing.Tags result = new com.strongdm.api.v1.plumbing.TagsPlumbing.Tags(this);
        int from_bitField0_ = bitField0_;
        if (pairsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            pairs_ = java.util.Collections.unmodifiableList(pairs_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.pairs_ = pairs_;
        } else {
          result.pairs_ = pairsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.strongdm.api.v1.plumbing.TagsPlumbing.Tags) {
          return mergeFrom((com.strongdm.api.v1.plumbing.TagsPlumbing.Tags)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.strongdm.api.v1.plumbing.TagsPlumbing.Tags other) {
        if (other == com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.getDefaultInstance()) return this;
        if (pairsBuilder_ == null) {
          if (!other.pairs_.isEmpty()) {
            if (pairs_.isEmpty()) {
              pairs_ = other.pairs_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePairsIsMutable();
              pairs_.addAll(other.pairs_);
            }
            onChanged();
          }
        } else {
          if (!other.pairs_.isEmpty()) {
            if (pairsBuilder_.isEmpty()) {
              pairsBuilder_.dispose();
              pairsBuilder_ = null;
              pairs_ = other.pairs_;
              bitField0_ = (bitField0_ & ~0x00000001);
              pairsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPairsFieldBuilder() : null;
            } else {
              pairsBuilder_.addAllMessages(other.pairs_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.strongdm.api.v1.plumbing.TagsPlumbing.Tags parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.strongdm.api.v1.plumbing.TagsPlumbing.Tags) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair> pairs_ =
        java.util.Collections.emptyList();
      private void ensurePairsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          pairs_ = new java.util.ArrayList<com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair>(pairs_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair, com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair.Builder, com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.PairOrBuilder> pairsBuilder_;

      /**
       * <code>repeated .v1.Tags.Pair pairs = 1;</code>
       */
      public java.util.List<com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair> getPairsList() {
        if (pairsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(pairs_);
        } else {
          return pairsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .v1.Tags.Pair pairs = 1;</code>
       */
      public int getPairsCount() {
        if (pairsBuilder_ == null) {
          return pairs_.size();
        } else {
          return pairsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .v1.Tags.Pair pairs = 1;</code>
       */
      public com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair getPairs(int index) {
        if (pairsBuilder_ == null) {
          return pairs_.get(index);
        } else {
          return pairsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .v1.Tags.Pair pairs = 1;</code>
       */
      public Builder setPairs(
          int index, com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair value) {
        if (pairsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePairsIsMutable();
          pairs_.set(index, value);
          onChanged();
        } else {
          pairsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .v1.Tags.Pair pairs = 1;</code>
       */
      public Builder setPairs(
          int index, com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair.Builder builderForValue) {
        if (pairsBuilder_ == null) {
          ensurePairsIsMutable();
          pairs_.set(index, builderForValue.build());
          onChanged();
        } else {
          pairsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .v1.Tags.Pair pairs = 1;</code>
       */
      public Builder addPairs(com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair value) {
        if (pairsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePairsIsMutable();
          pairs_.add(value);
          onChanged();
        } else {
          pairsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .v1.Tags.Pair pairs = 1;</code>
       */
      public Builder addPairs(
          int index, com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair value) {
        if (pairsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePairsIsMutable();
          pairs_.add(index, value);
          onChanged();
        } else {
          pairsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .v1.Tags.Pair pairs = 1;</code>
       */
      public Builder addPairs(
          com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair.Builder builderForValue) {
        if (pairsBuilder_ == null) {
          ensurePairsIsMutable();
          pairs_.add(builderForValue.build());
          onChanged();
        } else {
          pairsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .v1.Tags.Pair pairs = 1;</code>
       */
      public Builder addPairs(
          int index, com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair.Builder builderForValue) {
        if (pairsBuilder_ == null) {
          ensurePairsIsMutable();
          pairs_.add(index, builderForValue.build());
          onChanged();
        } else {
          pairsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .v1.Tags.Pair pairs = 1;</code>
       */
      public Builder addAllPairs(
          java.lang.Iterable<? extends com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair> values) {
        if (pairsBuilder_ == null) {
          ensurePairsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, pairs_);
          onChanged();
        } else {
          pairsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .v1.Tags.Pair pairs = 1;</code>
       */
      public Builder clearPairs() {
        if (pairsBuilder_ == null) {
          pairs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          pairsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .v1.Tags.Pair pairs = 1;</code>
       */
      public Builder removePairs(int index) {
        if (pairsBuilder_ == null) {
          ensurePairsIsMutable();
          pairs_.remove(index);
          onChanged();
        } else {
          pairsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .v1.Tags.Pair pairs = 1;</code>
       */
      public com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair.Builder getPairsBuilder(
          int index) {
        return getPairsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .v1.Tags.Pair pairs = 1;</code>
       */
      public com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.PairOrBuilder getPairsOrBuilder(
          int index) {
        if (pairsBuilder_ == null) {
          return pairs_.get(index);  } else {
          return pairsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .v1.Tags.Pair pairs = 1;</code>
       */
      public java.util.List<? extends com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.PairOrBuilder> 
           getPairsOrBuilderList() {
        if (pairsBuilder_ != null) {
          return pairsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(pairs_);
        }
      }
      /**
       * <code>repeated .v1.Tags.Pair pairs = 1;</code>
       */
      public com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair.Builder addPairsBuilder() {
        return getPairsFieldBuilder().addBuilder(
            com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair.getDefaultInstance());
      }
      /**
       * <code>repeated .v1.Tags.Pair pairs = 1;</code>
       */
      public com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair.Builder addPairsBuilder(
          int index) {
        return getPairsFieldBuilder().addBuilder(
            index, com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair.getDefaultInstance());
      }
      /**
       * <code>repeated .v1.Tags.Pair pairs = 1;</code>
       */
      public java.util.List<com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair.Builder> 
           getPairsBuilderList() {
        return getPairsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair, com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair.Builder, com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.PairOrBuilder> 
          getPairsFieldBuilder() {
        if (pairsBuilder_ == null) {
          pairsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair, com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.Pair.Builder, com.strongdm.api.v1.plumbing.TagsPlumbing.Tags.PairOrBuilder>(
                  pairs_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          pairs_ = null;
        }
        return pairsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:v1.Tags)
    }

    // @@protoc_insertion_point(class_scope:v1.Tags)
    private static final com.strongdm.api.v1.plumbing.TagsPlumbing.Tags DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.strongdm.api.v1.plumbing.TagsPlumbing.Tags();
    }

    public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tags getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Tags>
        PARSER = new com.google.protobuf.AbstractParser<Tags>() {
      @java.lang.Override
      public Tags parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Tags(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Tags> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Tags> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.strongdm.api.v1.plumbing.TagsPlumbing.Tags getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TagOrBuilder extends
      // @@protoc_insertion_point(interface_extends:v1.Tag)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1 [(.v1.field_options) = { ... }</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1 [(.v1.field_options) = { ... }</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string value = 2 [(.v1.field_options) = { ... }</code>
     * @return The value.
     */
    java.lang.String getValue();
    /**
     * <code>string value = 2 [(.v1.field_options) = { ... }</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code v1.Tag}
   */
  public static final class Tag extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:v1.Tag)
      TagOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Tag.newBuilder() to construct.
    private Tag(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Tag() {
      name_ = "";
      value_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Tag();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Tag(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              value_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.strongdm.api.v1.plumbing.TagsPlumbing.internal_static_v1_Tag_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.strongdm.api.v1.plumbing.TagsPlumbing.internal_static_v1_Tag_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.strongdm.api.v1.plumbing.TagsPlumbing.Tag.class, com.strongdm.api.v1.plumbing.TagsPlumbing.Tag.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1 [(.v1.field_options) = { ... }</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1 [(.v1.field_options) = { ... }</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private volatile java.lang.Object value_;
    /**
     * <code>string value = 2 [(.v1.field_options) = { ... }</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 2 [(.v1.field_options) = { ... }</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.strongdm.api.v1.plumbing.TagsPlumbing.Tag)) {
        return super.equals(obj);
      }
      com.strongdm.api.v1.plumbing.TagsPlumbing.Tag other = (com.strongdm.api.v1.plumbing.TagsPlumbing.Tag) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getValue()
          .equals(other.getValue())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tag parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tag parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tag parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tag parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tag parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tag parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tag parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tag parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tag parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tag parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tag parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tag parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.strongdm.api.v1.plumbing.TagsPlumbing.Tag prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code v1.Tag}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:v1.Tag)
        com.strongdm.api.v1.plumbing.TagsPlumbing.TagOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.strongdm.api.v1.plumbing.TagsPlumbing.internal_static_v1_Tag_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.strongdm.api.v1.plumbing.TagsPlumbing.internal_static_v1_Tag_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.strongdm.api.v1.plumbing.TagsPlumbing.Tag.class, com.strongdm.api.v1.plumbing.TagsPlumbing.Tag.Builder.class);
      }

      // Construct using com.strongdm.api.v1.plumbing.TagsPlumbing.Tag.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        value_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.strongdm.api.v1.plumbing.TagsPlumbing.internal_static_v1_Tag_descriptor;
      }

      @java.lang.Override
      public com.strongdm.api.v1.plumbing.TagsPlumbing.Tag getDefaultInstanceForType() {
        return com.strongdm.api.v1.plumbing.TagsPlumbing.Tag.getDefaultInstance();
      }

      @java.lang.Override
      public com.strongdm.api.v1.plumbing.TagsPlumbing.Tag build() {
        com.strongdm.api.v1.plumbing.TagsPlumbing.Tag result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.strongdm.api.v1.plumbing.TagsPlumbing.Tag buildPartial() {
        com.strongdm.api.v1.plumbing.TagsPlumbing.Tag result = new com.strongdm.api.v1.plumbing.TagsPlumbing.Tag(this);
        result.name_ = name_;
        result.value_ = value_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.strongdm.api.v1.plumbing.TagsPlumbing.Tag) {
          return mergeFrom((com.strongdm.api.v1.plumbing.TagsPlumbing.Tag)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.strongdm.api.v1.plumbing.TagsPlumbing.Tag other) {
        if (other == com.strongdm.api.v1.plumbing.TagsPlumbing.Tag.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.strongdm.api.v1.plumbing.TagsPlumbing.Tag parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.strongdm.api.v1.plumbing.TagsPlumbing.Tag) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1 [(.v1.field_options) = { ... }</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1 [(.v1.field_options) = { ... }</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1 [(.v1.field_options) = { ... }</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1 [(.v1.field_options) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1 [(.v1.field_options) = { ... }</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>string value = 2 [(.v1.field_options) = { ... }</code>
       * @return The value.
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value = 2 [(.v1.field_options) = { ... }</code>
       * @return The bytes for value.
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 2 [(.v1.field_options) = { ... }</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 2 [(.v1.field_options) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>string value = 2 [(.v1.field_options) = { ... }</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        value_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:v1.Tag)
    }

    // @@protoc_insertion_point(class_scope:v1.Tag)
    private static final com.strongdm.api.v1.plumbing.TagsPlumbing.Tag DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.strongdm.api.v1.plumbing.TagsPlumbing.Tag();
    }

    public static com.strongdm.api.v1.plumbing.TagsPlumbing.Tag getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Tag>
        PARSER = new com.google.protobuf.AbstractParser<Tag>() {
      @java.lang.Override
      public Tag parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Tag(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Tag> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Tag> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.strongdm.api.v1.plumbing.TagsPlumbing.Tag getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v1_Tags_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v1_Tags_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v1_Tags_Pair_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v1_Tags_Pair_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v1_Tag_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v1_Tag_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntags.proto\022\002v1\032\roptions.proto\"\320\004\n\004Tags" +
      "\022\034\n\005pairs\030\001 \003(\0132\r.v1.Tags.Pair\032\200\001\n\004Pair\022" +
      "\014\n\004name\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:[\372\370\263\007V\322\363\263\007\001" +
      "*\322\363\263\007\t!jopenapi\322\363\263\007\021!jopenapi_private\322\363\263" +
      "\007\r!json_gateway\322\363\263\007\025!json_gateway_privat" +
      "e:\246\003\372\370\263\007\240\003\312\363\263\007\304\002\352\363\263\007\004tags\362\363\263\007\n\n\002go\022\004Tags" +
      "\362\363\263\007\022\n\ngo_private\022\004Tags\362\363\263\007\024\n\014go_terrafo" +
      "rm\022\004Tags\362\363\263\007%\n\004java\022\035java.util.Map<Strin" +
      "g, String>\362\363\263\007\035\n\022terraform-provider\022\007Typ" +
      "eMap\362\363\263\007F\n\007openapi\022;{\"type\":\"object\", \"a" +
      "dditionalProperties\":{\"type\":\"string\"}}\362" +
      "\363\263\007!\n\014json_gateway\022\021map[string]string\362\363\263" +
      "\007)\n\024json_gateway_private\022\021map[string]str" +
      "ing\372\363\263\007\014tagsElemType\322\363\263\007\001*\322\363\263\007\t!jopenapi" +
      "\322\363\263\007\021!jopenapi_private\322\363\263\007\r!json_gateway" +
      "\322\363\263\007\025!json_gateway_private\"F\n\003Tag\022\030\n\004nam" +
      "e\030\001 \001(\tB\n\362\370\263\007\005\260\363\263\007\001\022\031\n\005value\030\002 \001(\tB\n\362\370\263\007" +
      "\005\260\363\263\007\001:\n\372\370\263\007\005\250\363\263\007\001Bc\n\034com.strongdm.api.v" +
      "1.plumbingB\014TagsPlumbingZ5github.com/str" +
      "ongdm/strongdm-sdk-go/v2/internal/v1;v1b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.strongdm.api.v1.plumbing.Options.getDescriptor(),
        });
    internal_static_v1_Tags_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_v1_Tags_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v1_Tags_descriptor,
        new java.lang.String[] { "Pairs", });
    internal_static_v1_Tags_Pair_descriptor =
      internal_static_v1_Tags_descriptor.getNestedTypes().get(0);
    internal_static_v1_Tags_Pair_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v1_Tags_Pair_descriptor,
        new java.lang.String[] { "Name", "Value", });
    internal_static_v1_Tag_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_v1_Tag_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v1_Tag_descriptor,
        new java.lang.String[] { "Name", "Value", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.strongdm.api.v1.plumbing.Options.fieldOptions);
    registry.add(com.strongdm.api.v1.plumbing.Options.messageOptions);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.strongdm.api.v1.plumbing.Options.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
