// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protogen. DO NOT EDIT.

package com.strongdm.api;

import java.util.Date;

/** AccessRequestConfig holds the information required to request access to a resource */
public class AccessRequestConfig {
  private String duration;
  /** The time access should end, defaults to the next occurance of 5 pm */
  public String getDuration() {
    return this.duration;
  }
  /** The time access should end, defaults to the next occurance of 5 pm */
  public void setDuration(String in) {
    this.duration = in;
  }

  private String reason;
  /** The reason for access */
  public String getReason() {
    return this.reason;
  }
  /** The reason for access */
  public void setReason(String in) {
    this.reason = in;
  }

  private String resourceId;
  /** The resource for which access is being requested */
  public String getResourceId() {
    return this.resourceId;
  }
  /** The resource for which access is being requested */
  public void setResourceId(String in) {
    this.resourceId = in;
  }

  private Date startFrom;
  /** The time access should start, defaults to now */
  public Date getStartFrom() {
    return this.startFrom;
  }
  /** The time access should start, defaults to now */
  public void setStartFrom(Date in) {
    this.startFrom = in;
  }
}
