// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protogen. DO NOT EDIT.

package com.strongdm.api;

import com.strongdm.api.plumbing.ApprovalWorkflowsGrpc;
import com.strongdm.api.plumbing.ApprovalWorkflowsPlumbing;
import com.strongdm.api.plumbing.PageIterator;
import com.strongdm.api.plumbing.PageResult;
import com.strongdm.api.plumbing.Plumbing;
import com.strongdm.api.plumbing.Spec.GetRequestMetadata;
import com.strongdm.api.plumbing.Spec.ListRequestMetadata;
import io.grpc.ManagedChannel;
import java.util.Iterator;
import java.util.List;
import java.util.concurrent.TimeUnit;
import java.util.function.Supplier;

/**
 * ApprovalWorkflows are the mechanism by which requests for access can be viewed by authorized
 * approvers and be approved or denied.
 */
public class ApprovalWorkflows implements SnapshotApprovalWorkflows {
  private final ApprovalWorkflowsGrpc.ApprovalWorkflowsBlockingStub stub;
  private final Client parent;

  public ApprovalWorkflows(ManagedChannel channel, Client client) {

    this.stub = ApprovalWorkflowsGrpc.newBlockingStub(channel);
    this.parent = client;
  }

  private ApprovalWorkflows(
      ApprovalWorkflowsGrpc.ApprovalWorkflowsBlockingStub stub, Client client) {
    this.stub = stub;
    this.parent = client;
  }

  /**
   * This function returns a copy of the ApprovalWorkflows service which has the given deadline set
   * for all method calls.
   */
  public ApprovalWorkflows withDeadlineAfter(long duration, TimeUnit units) {
    return new ApprovalWorkflows(this.stub.withDeadlineAfter(duration, units), this.parent);
  }
  /**
   * Create creates a new approval workflow and requires a name and approval mode for the approval
   * workflow.
   */
  public ApprovalWorkflowCreateResponse create(ApprovalWorkflow approvalWorkflow)
      throws RpcException {
    ApprovalWorkflowsPlumbing.ApprovalWorkflowCreateRequest.Builder builder =
        ApprovalWorkflowsPlumbing.ApprovalWorkflowCreateRequest.newBuilder();
    builder.setApprovalWorkflow(Plumbing.convertApprovalWorkflowToPlumbing(approvalWorkflow));
    ApprovalWorkflowsPlumbing.ApprovalWorkflowCreateRequest req = builder.build();
    ApprovalWorkflowsPlumbing.ApprovalWorkflowCreateResponse plumbingResponse;
    int tries = 0;
    while (true) {
      try {
        plumbingResponse =
            this.stub
                .withCallCredentials(
                    this.parent.getCallCredentials("ApprovalWorkflows.Create", req))
                .create(req);
      } catch (Exception e) {
        if (this.parent.shouldRetry(tries, e)) {
          tries++;
          this.parent.jitterSleep(tries);
          continue;
        }
        throw Plumbing.convertExceptionToPorcelain(e);
      }
      break;
    }
    return Plumbing.convertApprovalWorkflowCreateResponseToPorcelain(plumbingResponse);
  }
  /** Get reads one approval workflow by ID. */
  public ApprovalWorkflowGetResponse get(String id) throws RpcException {
    ApprovalWorkflowsPlumbing.ApprovalWorkflowGetRequest.Builder builder =
        ApprovalWorkflowsPlumbing.ApprovalWorkflowGetRequest.newBuilder();
    if (this.parent.snapshotDate != null) {
      GetRequestMetadata.Builder metaBuilder = GetRequestMetadata.newBuilder();
      metaBuilder.setSnapshotAt(Plumbing.convertTimestampToPlumbing(this.parent.snapshotDate));
      builder.setMeta(metaBuilder);
    }
    builder.setId((id));
    ApprovalWorkflowsPlumbing.ApprovalWorkflowGetRequest req = builder.build();
    ApprovalWorkflowsPlumbing.ApprovalWorkflowGetResponse plumbingResponse;
    int tries = 0;
    while (true) {
      try {
        plumbingResponse =
            this.stub
                .withCallCredentials(this.parent.getCallCredentials("ApprovalWorkflows.Get", req))
                .get(req);
      } catch (Exception e) {
        if (this.parent.shouldRetry(tries, e)) {
          tries++;
          this.parent.jitterSleep(tries);
          continue;
        }
        throw Plumbing.convertExceptionToPorcelain(e);
      }
      break;
    }
    return Plumbing.convertApprovalWorkflowGetResponseToPorcelain(plumbingResponse);
  }
  /** Delete deletes an existing approval workflow. */
  public ApprovalWorkflowDeleteResponse delete(String id) throws RpcException {
    ApprovalWorkflowsPlumbing.ApprovalWorkflowDeleteRequest.Builder builder =
        ApprovalWorkflowsPlumbing.ApprovalWorkflowDeleteRequest.newBuilder();
    builder.setId((id));
    ApprovalWorkflowsPlumbing.ApprovalWorkflowDeleteRequest req = builder.build();
    ApprovalWorkflowsPlumbing.ApprovalWorkflowDeleteResponse plumbingResponse;
    int tries = 0;
    while (true) {
      try {
        plumbingResponse =
            this.stub
                .withCallCredentials(
                    this.parent.getCallCredentials("ApprovalWorkflows.Delete", req))
                .delete(req);
      } catch (Exception e) {
        if (this.parent.shouldRetry(tries, e)) {
          tries++;
          this.parent.jitterSleep(tries);
          continue;
        }
        throw Plumbing.convertExceptionToPorcelain(e);
      }
      break;
    }
    return Plumbing.convertApprovalWorkflowDeleteResponseToPorcelain(plumbingResponse);
  }
  /** Update updates an existing approval workflow. */
  public ApprovalWorkflowUpdateResponse update(ApprovalWorkflow approvalWorkflow)
      throws RpcException {
    ApprovalWorkflowsPlumbing.ApprovalWorkflowUpdateRequest.Builder builder =
        ApprovalWorkflowsPlumbing.ApprovalWorkflowUpdateRequest.newBuilder();
    builder.setApprovalWorkflow(Plumbing.convertApprovalWorkflowToPlumbing(approvalWorkflow));
    ApprovalWorkflowsPlumbing.ApprovalWorkflowUpdateRequest req = builder.build();
    ApprovalWorkflowsPlumbing.ApprovalWorkflowUpdateResponse plumbingResponse;
    int tries = 0;
    while (true) {
      try {
        plumbingResponse =
            this.stub
                .withCallCredentials(
                    this.parent.getCallCredentials("ApprovalWorkflows.Update", req))
                .update(req);
      } catch (Exception e) {
        if (this.parent.shouldRetry(tries, e)) {
          tries++;
          this.parent.jitterSleep(tries);
          continue;
        }
        throw Plumbing.convertExceptionToPorcelain(e);
      }
      break;
    }
    return Plumbing.convertApprovalWorkflowUpdateResponseToPorcelain(plumbingResponse);
  }
  /** Lists existing approval workflows. */
  public Iterable<ApprovalWorkflow> list(String filter, Object... args) throws RpcException {
    ApprovalWorkflowsPlumbing.ApprovalWorkflowListRequest.Builder builder =
        ApprovalWorkflowsPlumbing.ApprovalWorkflowListRequest.newBuilder();
    builder.setFilter(Plumbing.quoteFilterArgs(filter, args));
    ListRequestMetadata.Builder metaBuilder = ListRequestMetadata.newBuilder();
    if (this.parent.pageLimit > 0) {
      metaBuilder.setLimit(this.parent.pageLimit);
    }
    if (this.parent.snapshotDate != null) {
      metaBuilder.setSnapshotAt(Plumbing.convertTimestampToPlumbing(this.parent.snapshotDate));
    }
    builder.setMeta(metaBuilder);

    Supplier<PageResult<ApprovalWorkflow>> pageFetcher =
        () -> {
          // Note: this closure captures and reuses the builder to set the next page
          ApprovalWorkflowsPlumbing.ApprovalWorkflowListRequest req = builder.build();
          ApprovalWorkflowsPlumbing.ApprovalWorkflowListResponse plumbingResponse;
          int tries = 0;
          while (true) {
            try {
              plumbingResponse =
                  this.stub
                      .withCallCredentials(
                          this.parent.getCallCredentials("ApprovalWorkflows.List", req))
                      .list(req);
            } catch (Exception e) {
              if (this.parent.shouldRetry(tries, e)) {
                tries++;
                this.parent.jitterSleep(tries);
                continue;
              }
              throw Plumbing.convertExceptionToPorcelain(e);
            }
            break;
          }

          List<ApprovalWorkflow> page =
              Plumbing.convertRepeatedApprovalWorkflowToPorcelain(
                  plumbingResponse.getApprovalWorkflowsList());

          boolean hasNextCursor = plumbingResponse.getMeta().getNextCursor() != "";
          builder.setMeta(
              ListRequestMetadata.newBuilder()
                  .setCursor(plumbingResponse.getMeta().getNextCursor()));

          return new PageResult<ApprovalWorkflow>(page, hasNextCursor);
        };

    Iterator<ApprovalWorkflow> iterator = new PageIterator<>(pageFetcher);

    return () -> iterator;
  }
}
