// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protogen. DO NOT EDIT.

package com.strongdm.api;

import com.strongdm.api.plumbing.ApprovalWorkflowApproversGrpc;
import com.strongdm.api.plumbing.ApprovalWorkflowApproversPlumbing;
import com.strongdm.api.plumbing.PageIterator;
import com.strongdm.api.plumbing.PageResult;
import com.strongdm.api.plumbing.Plumbing;
import com.strongdm.api.plumbing.Spec.GetRequestMetadata;
import com.strongdm.api.plumbing.Spec.ListRequestMetadata;
import io.grpc.Deadline;
import io.grpc.ManagedChannel;
import java.util.Iterator;
import java.util.List;
import java.util.concurrent.TimeUnit;
import java.util.function.Supplier;

/** ApprovalWorkflowApprovers link approval workflow approvers to an ApprovalWorkflowStep */
@Deprecated
public class ApprovalWorkflowApprovers implements SnapshotApprovalWorkflowApprovers {
  private final ApprovalWorkflowApproversGrpc.ApprovalWorkflowApproversBlockingStub stub;
  private final Client parent;
  private final Deadline deadline;

  public ApprovalWorkflowApprovers(ManagedChannel channel, Client client) {
    this.stub = ApprovalWorkflowApproversGrpc.newBlockingStub(channel);
    this.parent = client;
    this.deadline = null;
  }

  private ApprovalWorkflowApprovers(
      ApprovalWorkflowApproversGrpc.ApprovalWorkflowApproversBlockingStub stub,
      Client client,
      Deadline deadline) {
    this.stub = stub;
    this.parent = client;
    this.deadline = deadline;
  }

  /**
   * This function returns a copy of the ApprovalWorkflowApprovers service which has the given
   * deadline set for all method calls.
   */
  public ApprovalWorkflowApprovers withDeadlineAfter(long duration, TimeUnit units) {
    Deadline deadline = Deadline.after(duration, units);
    return new ApprovalWorkflowApprovers(this.stub.withDeadline(deadline), this.parent, deadline);
  }
  /** Deprecated: Create creates a new approval workflow approver. */
  public ApprovalWorkflowApproverCreateResponse create(
      ApprovalWorkflowApprover approvalWorkflowApprover) throws RpcException {
    ApprovalWorkflowApproversPlumbing.ApprovalWorkflowApproverCreateRequest.Builder builder =
        ApprovalWorkflowApproversPlumbing.ApprovalWorkflowApproverCreateRequest.newBuilder();
    builder.setApprovalWorkflowApprover(
        Plumbing.convertApprovalWorkflowApproverToPlumbing(approvalWorkflowApprover));
    ApprovalWorkflowApproversPlumbing.ApprovalWorkflowApproverCreateRequest req = builder.build();
    ApprovalWorkflowApproversPlumbing.ApprovalWorkflowApproverCreateResponse plumbingResponse;
    int tries = 0;
    while (true) {
      try {
        plumbingResponse =
            this.stub
                .withCallCredentials(
                    this.parent.getCallCredentials("ApprovalWorkflowApprovers.Create", req))
                .create(req);
      } catch (Exception e) {
        if (this.parent.shouldRetry(tries, e, this.deadline)) {
          tries++;
          try {
            Thread.sleep(this.parent.exponentialBackoff(tries, this.deadline));
          } catch (Exception ignored) {
          }
          continue;
        }
        throw Plumbing.convertExceptionToPorcelain(e);
      }
      break;
    }
    return Plumbing.convertApprovalWorkflowApproverCreateResponseToPorcelain(plumbingResponse);
  }
  /** Deprecated: Get reads one approval workflow approver by ID. */
  public ApprovalWorkflowApproverGetResponse get(String id) throws RpcException {
    ApprovalWorkflowApproversPlumbing.ApprovalWorkflowApproverGetRequest.Builder builder =
        ApprovalWorkflowApproversPlumbing.ApprovalWorkflowApproverGetRequest.newBuilder();
    if (this.parent.snapshotDate != null) {
      GetRequestMetadata.Builder metaBuilder = GetRequestMetadata.newBuilder();
      metaBuilder.setSnapshotAt(Plumbing.convertTimestampToPlumbing(this.parent.snapshotDate));
      builder.setMeta(metaBuilder);
    }
    builder.setId((id));
    ApprovalWorkflowApproversPlumbing.ApprovalWorkflowApproverGetRequest req = builder.build();
    ApprovalWorkflowApproversPlumbing.ApprovalWorkflowApproverGetResponse plumbingResponse;
    int tries = 0;
    while (true) {
      try {
        plumbingResponse =
            this.stub
                .withCallCredentials(
                    this.parent.getCallCredentials("ApprovalWorkflowApprovers.Get", req))
                .get(req);
      } catch (Exception e) {
        if (this.parent.shouldRetry(tries, e, this.deadline)) {
          tries++;
          try {
            Thread.sleep(this.parent.exponentialBackoff(tries, this.deadline));
          } catch (Exception ignored) {
          }
          continue;
        }
        throw Plumbing.convertExceptionToPorcelain(e);
      }
      break;
    }
    return Plumbing.convertApprovalWorkflowApproverGetResponseToPorcelain(plumbingResponse);
  }
  /** Deprecated: Delete deletes an existing approval workflow approver. */
  public ApprovalWorkflowApproverDeleteResponse delete(String id) throws RpcException {
    ApprovalWorkflowApproversPlumbing.ApprovalWorkflowApproverDeleteRequest.Builder builder =
        ApprovalWorkflowApproversPlumbing.ApprovalWorkflowApproverDeleteRequest.newBuilder();
    builder.setId((id));
    ApprovalWorkflowApproversPlumbing.ApprovalWorkflowApproverDeleteRequest req = builder.build();
    ApprovalWorkflowApproversPlumbing.ApprovalWorkflowApproverDeleteResponse plumbingResponse;
    int tries = 0;
    while (true) {
      try {
        plumbingResponse =
            this.stub
                .withCallCredentials(
                    this.parent.getCallCredentials("ApprovalWorkflowApprovers.Delete", req))
                .delete(req);
      } catch (Exception e) {
        if (this.parent.shouldRetry(tries, e, this.deadline)) {
          tries++;
          try {
            Thread.sleep(this.parent.exponentialBackoff(tries, this.deadline));
          } catch (Exception ignored) {
          }
          continue;
        }
        throw Plumbing.convertExceptionToPorcelain(e);
      }
      break;
    }
    return Plumbing.convertApprovalWorkflowApproverDeleteResponseToPorcelain(plumbingResponse);
  }
  /** Deprecated: Lists existing approval workflow approvers. */
  public Iterable<ApprovalWorkflowApprover> list(String filter, Object... args)
      throws RpcException {
    ApprovalWorkflowApproversPlumbing.ApprovalWorkflowApproverListRequest.Builder builder =
        ApprovalWorkflowApproversPlumbing.ApprovalWorkflowApproverListRequest.newBuilder();
    builder.setFilter(Plumbing.quoteFilterArgs(filter, args));
    ListRequestMetadata.Builder metaBuilder = ListRequestMetadata.newBuilder();
    if (this.parent.pageLimit > 0) {
      metaBuilder.setLimit(this.parent.pageLimit);
    }
    if (this.parent.snapshotDate != null) {
      metaBuilder.setSnapshotAt(Plumbing.convertTimestampToPlumbing(this.parent.snapshotDate));
    }
    builder.setMeta(metaBuilder);

    Supplier<PageResult<ApprovalWorkflowApprover>> pageFetcher =
        () -> {
          // Note: this closure captures and reuses the builder to set the next page
          ApprovalWorkflowApproversPlumbing.ApprovalWorkflowApproverListRequest req =
              builder.build();
          ApprovalWorkflowApproversPlumbing.ApprovalWorkflowApproverListResponse plumbingResponse;
          int tries = 0;
          while (true) {
            try {
              plumbingResponse =
                  this.stub
                      .withCallCredentials(
                          this.parent.getCallCredentials("ApprovalWorkflowApprovers.List", req))
                      .list(req);
            } catch (Exception e) {
              if (this.parent.shouldRetry(tries, e, this.deadline)) {
                tries++;
                try {
                  Thread.sleep(this.parent.exponentialBackoff(tries, this.deadline));
                } catch (Exception ignored) {
                }
                continue;
              }
              throw Plumbing.convertExceptionToPorcelain(e);
            }
            break;
          }

          List<ApprovalWorkflowApprover> page =
              Plumbing.convertRepeatedApprovalWorkflowApproverToPorcelain(
                  plumbingResponse.getApprovalWorkflowApproversList());

          boolean hasNextCursor = plumbingResponse.getMeta().getNextCursor() != "";
          builder.setMeta(
              ListRequestMetadata.newBuilder()
                  .setCursor(plumbingResponse.getMeta().getNextCursor()));

          return new PageResult<ApprovalWorkflowApprover>(page, hasNextCursor);
        };

    Iterator<ApprovalWorkflowApprover> iterator = new PageIterator<>(pageFetcher);

    return () -> iterator;
  }
}
