// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protogen. DO NOT EDIT.

package com.strongdm.api;

/** A Connector configures scanning for a given system. */
public interface Connector {
  /** Returns the unique identifier of the Connector. */
  String getId();
  /** Returns the name of the Connector. */
  String getName();
  /** Sets the name of the Connector. */
  void setName(String name);
  /** Returns the description of the Connector. */
  String getDescription();
  /** Sets the description of the Connector. */
  void setDescription(String description);
  /** Returns the services of the Connector. */
  Iterable<String> getServices();
  /** Sets the services of the Connector. */
  void setServices(Iterable<String> services);
  /** Returns the include tags of the Connector. */
  Iterable<Tag> getIncludeTags();
  /** Sets the include tags of the Connector. */
  void setIncludeTags(Iterable<Tag> includeTags);
  /** Returns the exclude tags of the Connector. */
  Iterable<Tag> getExcludeTags();
  /** Sets the exclude tags of the Connector. */
  void setExcludeTags(Iterable<Tag> excludeTags);
  /** Returns the scan period of the Connector. */
  String getScanPeriod();
  /** Sets the scan period of the Connector. */
  void setScanPeriod(String scanPeriod);
}
