// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protogen. DO NOT EDIT.

package com.strongdm.api;

import com.strongdm.api.plumbing.ControlPanelGrpc;
import com.strongdm.api.plumbing.ControlPanelPlumbing;
import com.strongdm.api.plumbing.Plumbing;
import io.grpc.Deadline;
import io.grpc.ManagedChannel;
import java.util.concurrent.TimeUnit;

/** ControlPanel contains all administrative controls. */
public class ControlPanel {
  private final ControlPanelGrpc.ControlPanelBlockingStub stub;
  private final Client parent;
  private final Deadline deadline;

  public ControlPanel(ManagedChannel channel, Client client) {
    this.stub = ControlPanelGrpc.newBlockingStub(channel);
    this.parent = client;
    this.deadline = null;
  }

  private ControlPanel(
      ControlPanelGrpc.ControlPanelBlockingStub stub, Client client, Deadline deadline) {
    this.stub = stub;
    this.parent = client;
    this.deadline = deadline;
  }

  /**
   * This function returns a copy of the ControlPanel service which has the given deadline set for
   * all method calls.
   */
  public ControlPanel withDeadlineAfter(long duration, TimeUnit units) {
    Deadline deadline = Deadline.after(duration, units);
    return new ControlPanel(this.stub.withDeadline(deadline), this.parent, deadline);
  }
  /** GetSSHCAPublicKey retrieves the SSH CA public key. */
  public ControlPanelGetSSHCAPublicKeyResponse getSSHCAPublicKey() throws RpcException {
    ControlPanelPlumbing.ControlPanelGetSSHCAPublicKeyRequest.Builder builder =
        ControlPanelPlumbing.ControlPanelGetSSHCAPublicKeyRequest.newBuilder();
    ControlPanelPlumbing.ControlPanelGetSSHCAPublicKeyRequest req = builder.build();
    // Execute before interceptor hooks
    req = this.parent.getInterceptor().executeBefore("ControlPanel.GetSSHCAPublicKey", req);
    ControlPanelPlumbing.ControlPanelGetSSHCAPublicKeyResponse plumbingResponse;
    int tries = 0;
    while (true) {
      try {
        plumbingResponse =
            this.stub
                .withCallCredentials(
                    this.parent.getCallCredentials("ControlPanel.GetSSHCAPublicKey", req))
                .getSSHCAPublicKey(req);
      } catch (Exception e) {
        if (this.parent.shouldRetry(tries, e, this.deadline)) {
          tries++;
          try {
            Thread.sleep(this.parent.exponentialBackoff(tries, this.deadline));
          } catch (Exception ignored) {
          }
          continue;
        }
        throw Plumbing.convertExceptionToPorcelain(e);
      }
      break;
    }
    // Execute after interceptor hooks
    plumbingResponse =
        this.parent
            .getInterceptor()
            .executeAfter("ControlPanel.GetSSHCAPublicKey", req, plumbingResponse);
    return Plumbing.convertControlPanelGetSSHCAPublicKeyResponseToPorcelain(plumbingResponse);
  }
  /** GetRDPCAPublicKey retrieves the RDP CA public key. */
  public ControlPanelGetRDPCAPublicKeyResponse getRDPCAPublicKey() throws RpcException {
    ControlPanelPlumbing.ControlPanelGetRDPCAPublicKeyRequest.Builder builder =
        ControlPanelPlumbing.ControlPanelGetRDPCAPublicKeyRequest.newBuilder();
    ControlPanelPlumbing.ControlPanelGetRDPCAPublicKeyRequest req = builder.build();
    // Execute before interceptor hooks
    req = this.parent.getInterceptor().executeBefore("ControlPanel.GetRDPCAPublicKey", req);
    ControlPanelPlumbing.ControlPanelGetRDPCAPublicKeyResponse plumbingResponse;
    int tries = 0;
    while (true) {
      try {
        plumbingResponse =
            this.stub
                .withCallCredentials(
                    this.parent.getCallCredentials("ControlPanel.GetRDPCAPublicKey", req))
                .getRDPCAPublicKey(req);
      } catch (Exception e) {
        if (this.parent.shouldRetry(tries, e, this.deadline)) {
          tries++;
          try {
            Thread.sleep(this.parent.exponentialBackoff(tries, this.deadline));
          } catch (Exception ignored) {
          }
          continue;
        }
        throw Plumbing.convertExceptionToPorcelain(e);
      }
      break;
    }
    // Execute after interceptor hooks
    plumbingResponse =
        this.parent
            .getInterceptor()
            .executeAfter("ControlPanel.GetRDPCAPublicKey", req, plumbingResponse);
    return Plumbing.convertControlPanelGetRDPCAPublicKeyResponseToPorcelain(plumbingResponse);
  }
  /** VerifyJWT reports whether the given JWT token (x-sdm-token) is valid. */
  public ControlPanelVerifyJWTResponse verifyJWT(String token) throws RpcException {
    ControlPanelPlumbing.ControlPanelVerifyJWTRequest.Builder builder =
        ControlPanelPlumbing.ControlPanelVerifyJWTRequest.newBuilder();
    builder.setToken((token));
    ControlPanelPlumbing.ControlPanelVerifyJWTRequest req = builder.build();
    // Execute before interceptor hooks
    req = this.parent.getInterceptor().executeBefore("ControlPanel.VerifyJWT", req);
    ControlPanelPlumbing.ControlPanelVerifyJWTResponse plumbingResponse;
    int tries = 0;
    while (true) {
      try {
        plumbingResponse =
            this.stub
                .withCallCredentials(this.parent.getCallCredentials("ControlPanel.VerifyJWT", req))
                .verifyJWT(req);
      } catch (Exception e) {
        if (this.parent.shouldRetry(tries, e, this.deadline)) {
          tries++;
          try {
            Thread.sleep(this.parent.exponentialBackoff(tries, this.deadline));
          } catch (Exception ignored) {
          }
          continue;
        }
        throw Plumbing.convertExceptionToPorcelain(e);
      }
      break;
    }
    // Execute after interceptor hooks
    plumbingResponse =
        this.parent.getInterceptor().executeAfter("ControlPanel.VerifyJWT", req, plumbingResponse);
    return Plumbing.convertControlPanelVerifyJWTResponseToPorcelain(plumbingResponse);
  }
}
