// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protogen. DO NOT EDIT.

package com.strongdm.api;

/** CustomHeader describes a single HTTP header */
public class CustomHeader {
  private String name;
  /** The name of this header. */
  public String getName() {
    return this.name;
  }
  /** The name of this header. */
  public void setName(String in) {
    this.name = in;
  }

  private boolean secret;
  /** Headers containing sensitive values must be stored encrypted and redacted from logs. */
  public boolean getSecret() {
    return this.secret;
  }
  /** Headers containing sensitive values must be stored encrypted and redacted from logs. */
  public void setSecret(boolean in) {
    this.secret = in;
  }

  private String value;
  /** The value of this header. */
  public String getValue() {
    return this.value;
  }
  /** The value of this header. */
  public void setValue(String in) {
    this.value = in;
  }
}
