// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protogen. DO NOT EDIT.

package com.strongdm.api;

import java.util.Date;

/**
 * GrantedResourceEntitlement represents an individual entitlement of an Account to a Resource,
 * viewed from the resource's perspective.
 */
public class GrantedResourceEntitlement {
  private String accountId;
  /** The unique identifier of the Account that has access to this resource. */
  public String getAccountId() {
    return this.accountId;
  }
  /** The unique identifier of the Account that has access to this resource. */
  public void setAccountId(String in) {
    this.accountId = in;
  }

  private String groupId;
  /** The unique identifier of the group associated with this entitlement, if any. */
  public String getGroupId() {
    return this.groupId;
  }
  /** The unique identifier of the group associated with this entitlement, if any. */
  public void setGroupId(String in) {
    this.groupId = in;
  }

  private Date lastAccessed;
  /**
   * The most recent time at which the account accessed this resource. Empty if the resource has
   * never been accessed.
   */
  public Date getLastAccessed() {
    return this.lastAccessed;
  }
  /**
   * The most recent time at which the account accessed this resource. Empty if the resource has
   * never been accessed.
   */
  public void setLastAccessed(Date in) {
    this.lastAccessed = in;
  }

  private MappedIdentities mappedIdentities;
  /** The mapped identity privileges for this entitlement, such as Kubernetes group memberships. */
  public MappedIdentities getMappedIdentities() {
    return this.mappedIdentities;
  }
  /** The mapped identity privileges for this entitlement, such as Kubernetes group memberships. */
  public void setMappedIdentities(MappedIdentities in) {
    this.mappedIdentities = in;
  }

  private String originId;
  /** The unique identifier of the origin of this entitlement (e.g., a Role or AccountGrant ID). */
  public String getOriginId() {
    return this.originId;
  }
  /** The unique identifier of the origin of this entitlement (e.g., a Role or AccountGrant ID). */
  public void setOriginId(String in) {
    this.originId = in;
  }
}
