// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protogen. DO NOT EDIT.

package com.strongdm.api;

import java.util.List;

public class GroupFromRole {
  private List<User> accounts;
  /** The migrated Accounts. */
  public List<User> getAccounts() {
    return this.accounts;
  }
  /** The migrated Accounts. */
  public void setAccounts(List<User> in) {
    this.accounts = in;
  }

  private List<ApprovalWorkflow> approvalFlows;
  /** The affected approval flows. */
  public List<ApprovalWorkflow> getApprovalFlows() {
    return this.approvalFlows;
  }
  /** The affected approval flows. */
  public void setApprovalFlows(List<ApprovalWorkflow> in) {
    this.approvalFlows = in;
  }

  private Group group;
  /** The group created from the source role. */
  public Group getGroup() {
    return this.group;
  }
  /** The group created from the source role. */
  public void setGroup(Group in) {
    this.group = in;
  }

  private RateLimitMetadata rateLimit;
  /** Rate limit information. */
  public RateLimitMetadata getRateLimit() {
    return this.rateLimit;
  }
  /** Rate limit information. */
  public void setRateLimit(RateLimitMetadata in) {
    this.rateLimit = in;
  }

  private Role role;
  /** The source role. */
  public Role getRole() {
    return this.role;
  }
  /** The source role. */
  public void setRole(Role in) {
    this.role = in;
  }
}
