// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protogen. DO NOT EDIT.

package com.strongdm.api;

import com.strongdm.api.plumbing.GroupsRolesGrpc;
import com.strongdm.api.plumbing.GroupsRolesPlumbing;
import com.strongdm.api.plumbing.PageIterator;
import com.strongdm.api.plumbing.PageResult;
import com.strongdm.api.plumbing.Plumbing;
import com.strongdm.api.plumbing.Spec.GetRequestMetadata;
import com.strongdm.api.plumbing.Spec.ListRequestMetadata;
import io.grpc.Deadline;
import io.grpc.ManagedChannel;
import java.util.Iterator;
import java.util.List;
import java.util.concurrent.TimeUnit;
import java.util.function.Supplier;

/** A GroupRole is an assignment of a Group to a Role. */
public class GroupsRoles implements SnapshotGroupsRoles {
  private final GroupsRolesGrpc.GroupsRolesBlockingStub stub;
  private final Client parent;
  private final Deadline deadline;

  public GroupsRoles(ManagedChannel channel, Client client) {
    this.stub = GroupsRolesGrpc.newBlockingStub(channel);
    this.parent = client;
    this.deadline = null;
  }

  private GroupsRoles(
      GroupsRolesGrpc.GroupsRolesBlockingStub stub, Client client, Deadline deadline) {
    this.stub = stub;
    this.parent = client;
    this.deadline = deadline;
  }

  /**
   * This function returns a copy of the GroupsRoles service which has the given deadline set for
   * all method calls.
   */
  public GroupsRoles withDeadlineAfter(long duration, TimeUnit units) {
    Deadline deadline = Deadline.after(duration, units);
    return new GroupsRoles(this.stub.withDeadline(deadline), this.parent, deadline);
  }
  /** Create registers a new GroupRole. */
  public GroupRoleCreateResponse create(GroupRole groupRole) throws RpcException {
    GroupsRolesPlumbing.GroupRoleCreateRequest.Builder builder =
        GroupsRolesPlumbing.GroupRoleCreateRequest.newBuilder();
    builder.setGroupRole(Plumbing.convertGroupRoleToPlumbing(groupRole));
    GroupsRolesPlumbing.GroupRoleCreateRequest req = builder.build();
    // Execute before interceptor hooks
    req = this.parent.getInterceptor().executeBefore("GroupsRoles.Create", req);
    GroupsRolesPlumbing.GroupRoleCreateResponse plumbingResponse;
    int tries = 0;
    while (true) {
      try {
        plumbingResponse =
            this.stub
                .withCallCredentials(this.parent.getCallCredentials("GroupsRoles.Create", req))
                .create(req);
      } catch (Exception e) {
        if (this.parent.shouldRetry(tries, e, this.deadline)) {
          tries++;
          try {
            Thread.sleep(this.parent.exponentialBackoff(tries, this.deadline));
          } catch (Exception ignored) {
          }
          continue;
        }
        throw Plumbing.convertExceptionToPorcelain(e);
      }
      break;
    }
    // Execute after interceptor hooks
    plumbingResponse =
        this.parent.getInterceptor().executeAfter("GroupsRoles.Create", req, plumbingResponse);
    return Plumbing.convertGroupRoleCreateResponseToPorcelain(plumbingResponse);
  }
  /** Get reads one GroupRole by ID. */
  public GroupRoleGetResponse get(String id) throws RpcException {
    GroupsRolesPlumbing.GroupRoleGetRequest.Builder builder =
        GroupsRolesPlumbing.GroupRoleGetRequest.newBuilder();
    if (this.parent.snapshotDate != null) {
      GetRequestMetadata.Builder metaBuilder = GetRequestMetadata.newBuilder();
      metaBuilder.setSnapshotAt(Plumbing.convertTimestampToPlumbing(this.parent.snapshotDate));
      builder.setMeta(metaBuilder);
    }
    builder.setId((id));
    GroupsRolesPlumbing.GroupRoleGetRequest req = builder.build();
    // Execute before interceptor hooks
    req = this.parent.getInterceptor().executeBefore("GroupsRoles.Get", req);
    GroupsRolesPlumbing.GroupRoleGetResponse plumbingResponse;
    int tries = 0;
    while (true) {
      try {
        plumbingResponse =
            this.stub
                .withCallCredentials(this.parent.getCallCredentials("GroupsRoles.Get", req))
                .get(req);
      } catch (Exception e) {
        if (this.parent.shouldRetry(tries, e, this.deadline)) {
          tries++;
          try {
            Thread.sleep(this.parent.exponentialBackoff(tries, this.deadline));
          } catch (Exception ignored) {
          }
          continue;
        }
        throw Plumbing.convertExceptionToPorcelain(e);
      }
      break;
    }
    // Execute after interceptor hooks
    plumbingResponse =
        this.parent.getInterceptor().executeAfter("GroupsRoles.Get", req, plumbingResponse);
    return Plumbing.convertGroupRoleGetResponseToPorcelain(plumbingResponse);
  }
  /** Delete removes a GroupRole by ID. */
  public GroupRoleDeleteResponse delete(String id) throws RpcException {
    GroupsRolesPlumbing.GroupRoleDeleteRequest.Builder builder =
        GroupsRolesPlumbing.GroupRoleDeleteRequest.newBuilder();
    builder.setId((id));
    GroupsRolesPlumbing.GroupRoleDeleteRequest req = builder.build();
    // Execute before interceptor hooks
    req = this.parent.getInterceptor().executeBefore("GroupsRoles.Delete", req);
    GroupsRolesPlumbing.GroupRoleDeleteResponse plumbingResponse;
    int tries = 0;
    while (true) {
      try {
        plumbingResponse =
            this.stub
                .withCallCredentials(this.parent.getCallCredentials("GroupsRoles.Delete", req))
                .delete(req);
      } catch (Exception e) {
        if (this.parent.shouldRetry(tries, e, this.deadline)) {
          tries++;
          try {
            Thread.sleep(this.parent.exponentialBackoff(tries, this.deadline));
          } catch (Exception ignored) {
          }
          continue;
        }
        throw Plumbing.convertExceptionToPorcelain(e);
      }
      break;
    }
    // Execute after interceptor hooks
    plumbingResponse =
        this.parent.getInterceptor().executeAfter("GroupsRoles.Delete", req, plumbingResponse);
    return Plumbing.convertGroupRoleDeleteResponseToPorcelain(plumbingResponse);
  }
  /** List gets a list of GroupRoles matching a given set of criteria. */
  public Iterable<GroupRole> list(String filter, Object... args) throws RpcException {
    GroupsRolesPlumbing.GroupRoleListRequest.Builder builder =
        GroupsRolesPlumbing.GroupRoleListRequest.newBuilder();
    builder.setFilter(Plumbing.quoteFilterArgs(filter, args));
    ListRequestMetadata.Builder metaBuilder = ListRequestMetadata.newBuilder();
    if (this.parent.pageLimit > 0) {
      metaBuilder.setLimit(this.parent.pageLimit);
    }
    if (this.parent.snapshotDate != null) {
      metaBuilder.setSnapshotAt(Plumbing.convertTimestampToPlumbing(this.parent.snapshotDate));
    }
    builder.setMeta(metaBuilder);

    Supplier<PageResult<GroupRole>> pageFetcher =
        () -> {
          // Note: this closure captures and reuses the builder to set the next page
          GroupsRolesPlumbing.GroupRoleListRequest req = builder.build();
          GroupsRolesPlumbing.GroupRoleListResponse plumbingResponse;
          int tries = 0;
          while (true) {
            try {
              plumbingResponse =
                  this.stub
                      .withCallCredentials(this.parent.getCallCredentials("GroupsRoles.List", req))
                      .list(req);
            } catch (Exception e) {
              if (this.parent.shouldRetry(tries, e, this.deadline)) {
                tries++;
                try {
                  Thread.sleep(this.parent.exponentialBackoff(tries, this.deadline));
                } catch (Exception ignored) {
                }
                continue;
              }
              throw Plumbing.convertExceptionToPorcelain(e);
            }
            break;
          }

          List<GroupRole> page =
              Plumbing.convertRepeatedGroupRoleToPorcelain(plumbingResponse.getGroupsRolesList());

          boolean hasNextCursor = plumbingResponse.getMeta().getNextCursor() != "";
          builder.setMeta(
              ListRequestMetadata.newBuilder()
                  .setCursor(plumbingResponse.getMeta().getNextCursor()));

          return new PageResult<GroupRole>(page, hasNextCursor);
        };

    Iterator<GroupRole> iterator = new PageIterator<>(pageFetcher);

    return () -> iterator;
  }
}
