// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protogen. DO NOT EDIT.

package com.strongdm.api;

import com.strongdm.api.plumbing.IdentitySetsHistoryGrpc;
import com.strongdm.api.plumbing.IdentitySetsHistoryPlumbing;
import com.strongdm.api.plumbing.PageIterator;
import com.strongdm.api.plumbing.PageResult;
import com.strongdm.api.plumbing.Plumbing;
import com.strongdm.api.plumbing.Spec.ListRequestMetadata;
import io.grpc.ManagedChannel;
import java.util.Iterator;
import java.util.List;
import java.util.concurrent.TimeUnit;
import java.util.function.Supplier;

/** IdentitySetsHistory records all changes to the state of a IdentitySet. */
public class IdentitySetsHistory {
  private final IdentitySetsHistoryGrpc.IdentitySetsHistoryBlockingStub stub;
  private final Client parent;

  public IdentitySetsHistory(ManagedChannel channel, Client client) {

    this.stub = IdentitySetsHistoryGrpc.newBlockingStub(channel);
    this.parent = client;
  }

  private IdentitySetsHistory(
      IdentitySetsHistoryGrpc.IdentitySetsHistoryBlockingStub stub, Client client) {
    this.stub = stub;
    this.parent = client;
  }

  /**
   * This function returns a copy of the IdentitySetsHistory service which has the given deadline
   * set for all method calls.
   */
  public IdentitySetsHistory withDeadlineAfter(long duration, TimeUnit units) {
    return new IdentitySetsHistory(this.stub.withDeadlineAfter(duration, units), this.parent);
  }
  /** List gets a list of IdentitySetHistory records matching a given set of criteria. */
  public Iterable<IdentitySetHistory> list(String filter, Object... args) throws RpcException {
    IdentitySetsHistoryPlumbing.IdentitySetHistoryListRequest.Builder builder =
        IdentitySetsHistoryPlumbing.IdentitySetHistoryListRequest.newBuilder();
    builder.setFilter(Plumbing.quoteFilterArgs(filter, args));
    ListRequestMetadata.Builder metaBuilder = ListRequestMetadata.newBuilder();
    if (this.parent.pageLimit > 0) {
      metaBuilder.setLimit(this.parent.pageLimit);
    }
    if (this.parent.snapshotDate != null) {
      metaBuilder.setSnapshotAt(Plumbing.convertTimestampToPlumbing(this.parent.snapshotDate));
    }
    builder.setMeta(metaBuilder);

    Supplier<PageResult<IdentitySetHistory>> pageFetcher =
        () -> {
          // Note: this closure captures and reuses the builder to set the next page
          IdentitySetsHistoryPlumbing.IdentitySetHistoryListRequest req = builder.build();
          IdentitySetsHistoryPlumbing.IdentitySetHistoryListResponse plumbingResponse;
          int tries = 0;
          while (true) {
            try {
              plumbingResponse =
                  this.stub
                      .withCallCredentials(
                          this.parent.getCallCredentials("IdentitySetsHistory.List", req))
                      .list(req);
            } catch (Exception e) {
              if (this.parent.shouldRetry(tries, e)) {
                tries++;
                this.parent.jitterSleep(tries);
                continue;
              }
              throw Plumbing.convertExceptionToPorcelain(e);
            }
            break;
          }

          List<IdentitySetHistory> page =
              Plumbing.convertRepeatedIdentitySetHistoryToPorcelain(
                  plumbingResponse.getHistoryList());

          boolean hasNextCursor = plumbingResponse.getMeta().getNextCursor() != "";
          builder.setMeta(
              ListRequestMetadata.newBuilder()
                  .setCursor(plumbingResponse.getMeta().getNextCursor()));

          return new PageResult<IdentitySetHistory>(page, hasNextCursor);
        };

    Iterator<IdentitySetHistory> iterator = new PageIterator<>(pageFetcher);

    return () -> iterator;
  }
}
