// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protogen. DO NOT EDIT.

package com.strongdm.api;

import com.strongdm.api.plumbing.IdentityAliasesGrpc;
import com.strongdm.api.plumbing.IdentityAliasesPlumbing;
import com.strongdm.api.plumbing.PageIterator;
import com.strongdm.api.plumbing.PageResult;
import com.strongdm.api.plumbing.Plumbing;
import com.strongdm.api.plumbing.Spec.GetRequestMetadata;
import com.strongdm.api.plumbing.Spec.ListRequestMetadata;
import io.grpc.ManagedChannel;
import java.util.Iterator;
import java.util.List;
import java.util.concurrent.TimeUnit;
import java.util.function.Supplier;

/**
 * IdentityAliases assign an alias to an account within an IdentitySet. The alias is used as the
 * username when connecting to a identity supported resource.
 */
public class IdentityAliases implements SnapshotIdentityAliases {
  private final IdentityAliasesGrpc.IdentityAliasesBlockingStub stub;
  private final Client parent;

  public IdentityAliases(ManagedChannel channel, Client client) {

    this.stub = IdentityAliasesGrpc.newBlockingStub(channel);
    this.parent = client;
  }

  private IdentityAliases(IdentityAliasesGrpc.IdentityAliasesBlockingStub stub, Client client) {
    this.stub = stub;
    this.parent = client;
  }

  /**
   * This function returns a copy of the IdentityAliases service which has the given deadline set
   * for all method calls.
   */
  public IdentityAliases withDeadlineAfter(long duration, TimeUnit units) {
    return new IdentityAliases(this.stub.withDeadlineAfter(duration, units), this.parent);
  }
  /** Create registers a new IdentityAlias. */
  public IdentityAliasCreateResponse create(IdentityAlias identityAlias) throws RpcException {
    IdentityAliasesPlumbing.IdentityAliasCreateRequest.Builder builder =
        IdentityAliasesPlumbing.IdentityAliasCreateRequest.newBuilder();
    builder.setIdentityAlias(Plumbing.convertIdentityAliasToPlumbing(identityAlias));
    IdentityAliasesPlumbing.IdentityAliasCreateRequest req = builder.build();
    IdentityAliasesPlumbing.IdentityAliasCreateResponse plumbingResponse;
    int tries = 0;
    while (true) {
      try {
        plumbingResponse =
            this.stub
                .withCallCredentials(this.parent.getCallCredentials("IdentityAliases.Create", req))
                .create(req);
      } catch (Exception e) {
        if (this.parent.shouldRetry(tries, e)) {
          tries++;
          this.parent.jitterSleep(tries);
          continue;
        }
        throw Plumbing.convertExceptionToPorcelain(e);
      }
      break;
    }
    return Plumbing.convertIdentityAliasCreateResponseToPorcelain(plumbingResponse);
  }
  /** Get reads one IdentityAlias by ID. */
  public IdentityAliasGetResponse get(String id) throws RpcException {
    IdentityAliasesPlumbing.IdentityAliasGetRequest.Builder builder =
        IdentityAliasesPlumbing.IdentityAliasGetRequest.newBuilder();
    if (this.parent.snapshotDate != null) {
      GetRequestMetadata.Builder metaBuilder = GetRequestMetadata.newBuilder();
      metaBuilder.setSnapshotAt(Plumbing.convertTimestampToPlumbing(this.parent.snapshotDate));
      builder.setMeta(metaBuilder);
    }
    builder.setId((id));
    IdentityAliasesPlumbing.IdentityAliasGetRequest req = builder.build();
    IdentityAliasesPlumbing.IdentityAliasGetResponse plumbingResponse;
    int tries = 0;
    while (true) {
      try {
        plumbingResponse =
            this.stub
                .withCallCredentials(this.parent.getCallCredentials("IdentityAliases.Get", req))
                .get(req);
      } catch (Exception e) {
        if (this.parent.shouldRetry(tries, e)) {
          tries++;
          this.parent.jitterSleep(tries);
          continue;
        }
        throw Plumbing.convertExceptionToPorcelain(e);
      }
      break;
    }
    return Plumbing.convertIdentityAliasGetResponseToPorcelain(plumbingResponse);
  }
  /** Update replaces all the fields of a IdentityAlias by ID. */
  public IdentityAliasUpdateResponse update(IdentityAlias identityAlias) throws RpcException {
    IdentityAliasesPlumbing.IdentityAliasUpdateRequest.Builder builder =
        IdentityAliasesPlumbing.IdentityAliasUpdateRequest.newBuilder();
    builder.setIdentityAlias(Plumbing.convertIdentityAliasToPlumbing(identityAlias));
    IdentityAliasesPlumbing.IdentityAliasUpdateRequest req = builder.build();
    IdentityAliasesPlumbing.IdentityAliasUpdateResponse plumbingResponse;
    int tries = 0;
    while (true) {
      try {
        plumbingResponse =
            this.stub
                .withCallCredentials(this.parent.getCallCredentials("IdentityAliases.Update", req))
                .update(req);
      } catch (Exception e) {
        if (this.parent.shouldRetry(tries, e)) {
          tries++;
          this.parent.jitterSleep(tries);
          continue;
        }
        throw Plumbing.convertExceptionToPorcelain(e);
      }
      break;
    }
    return Plumbing.convertIdentityAliasUpdateResponseToPorcelain(plumbingResponse);
  }
  /** Delete removes a IdentityAlias by ID. */
  public IdentityAliasDeleteResponse delete(String id) throws RpcException {
    IdentityAliasesPlumbing.IdentityAliasDeleteRequest.Builder builder =
        IdentityAliasesPlumbing.IdentityAliasDeleteRequest.newBuilder();
    builder.setId((id));
    IdentityAliasesPlumbing.IdentityAliasDeleteRequest req = builder.build();
    IdentityAliasesPlumbing.IdentityAliasDeleteResponse plumbingResponse;
    int tries = 0;
    while (true) {
      try {
        plumbingResponse =
            this.stub
                .withCallCredentials(this.parent.getCallCredentials("IdentityAliases.Delete", req))
                .delete(req);
      } catch (Exception e) {
        if (this.parent.shouldRetry(tries, e)) {
          tries++;
          this.parent.jitterSleep(tries);
          continue;
        }
        throw Plumbing.convertExceptionToPorcelain(e);
      }
      break;
    }
    return Plumbing.convertIdentityAliasDeleteResponseToPorcelain(plumbingResponse);
  }
  /** List gets a list of IdentityAliases matching a given set of criteria. */
  public Iterable<IdentityAlias> list(String filter, Object... args) throws RpcException {
    IdentityAliasesPlumbing.IdentityAliasListRequest.Builder builder =
        IdentityAliasesPlumbing.IdentityAliasListRequest.newBuilder();
    builder.setFilter(Plumbing.quoteFilterArgs(filter, args));
    ListRequestMetadata.Builder metaBuilder = ListRequestMetadata.newBuilder();
    if (this.parent.pageLimit > 0) {
      metaBuilder.setLimit(this.parent.pageLimit);
    }
    if (this.parent.snapshotDate != null) {
      metaBuilder.setSnapshotAt(Plumbing.convertTimestampToPlumbing(this.parent.snapshotDate));
    }
    builder.setMeta(metaBuilder);

    Supplier<PageResult<IdentityAlias>> pageFetcher =
        () -> {
          // Note: this closure captures and reuses the builder to set the next page
          IdentityAliasesPlumbing.IdentityAliasListRequest req = builder.build();
          IdentityAliasesPlumbing.IdentityAliasListResponse plumbingResponse;
          int tries = 0;
          while (true) {
            try {
              plumbingResponse =
                  this.stub
                      .withCallCredentials(
                          this.parent.getCallCredentials("IdentityAliases.List", req))
                      .list(req);
            } catch (Exception e) {
              if (this.parent.shouldRetry(tries, e)) {
                tries++;
                this.parent.jitterSleep(tries);
                continue;
              }
              throw Plumbing.convertExceptionToPorcelain(e);
            }
            break;
          }

          List<IdentityAlias> page =
              Plumbing.convertRepeatedIdentityAliasToPorcelain(
                  plumbingResponse.getIdentityAliasesList());

          boolean hasNextCursor = plumbingResponse.getMeta().getNextCursor() != "";
          builder.setMeta(
              ListRequestMetadata.newBuilder()
                  .setCursor(plumbingResponse.getMeta().getNextCursor()));

          return new PageResult<IdentityAlias>(page, hasNextCursor);
        };

    Iterator<IdentityAlias> iterator = new PageIterator<>(pageFetcher);

    return () -> iterator;
  }
}
