// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protogen. DO NOT EDIT.

package com.strongdm.api;

/** ManagedSecretRetrieveRequest specifies which Managed Secret to retrieve */
public class ManagedSecretRetrieveRequest {
  private String id;
  /** The unique identifier of the Managed Secret to retrieve. */
  public String getId() {
    return this.id;
  }
  /** The unique identifier of the Managed Secret to retrieve. */
  public void setId(String in) {
    this.id = in;
  }

  private byte[] publicKey;
  /** Public key to encrypt a sensitive value with */
  public byte[] getPublicKey() {
    return this.publicKey;
  }
  /** Public key to encrypt a sensitive value with */
  public void setPublicKey(byte[] in) {
    this.publicKey = in;
  }
}
