// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protogen. DO NOT EDIT.

package com.strongdm.api;

/** ManagedSecretPolicy contains password and rotation policy for managed secret */
public class ManagedSecretPolicy {
  private ManagedSecretPasswordPolicy passwordPolicy;
  /** Password policy for a managed secret */
  public ManagedSecretPasswordPolicy getPasswordPolicy() {
    return this.passwordPolicy;
  }
  /** Password policy for a managed secret */
  public void setPasswordPolicy(ManagedSecretPasswordPolicy in) {
    this.passwordPolicy = in;
  }

  private ManagedSecretRotationPolicy rotationPolicy;
  /** Rotation policy for a managed secret */
  public ManagedSecretRotationPolicy getRotationPolicy() {
    return this.rotationPolicy;
  }
  /** Rotation policy for a managed secret */
  public void setRotationPolicy(ManagedSecretRotationPolicy in) {
    this.rotationPolicy = in;
  }
}
