// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by protogen. DO NOT EDIT.

package com.strongdm.api;

import com.google.protobuf.Message;
import java.util.HashMap;
import java.util.Map;

/**
 * MethodInterceptor provides a generic hook system for modifying requests and responses
 * before/after gRPC calls.
 */
class MethodInterceptor {

  @FunctionalInterface
  interface BeforeHook<T extends Message> {
    T apply(T request);
  }

  @FunctionalInterface
  interface AfterHook<Req extends Message, Resp extends Message> {
    Resp apply(Req request, Resp response);
  }

  private final Map<String, BeforeHook<?>> beforeHooks = new HashMap<>();
  private final Map<String, AfterHook<?, ?>> afterHooks = new HashMap<>();

  /**
   * Register a hook to run before a method call.
   *
   * @param methodName Format: "ServiceName.MethodName" (e.g., "ManagedSecrets.Create")
   * @param hook receives request and returns modified request
   */
  <T extends Message> void before(String methodName, BeforeHook<T> hook) {
    beforeHooks.put(methodName, hook);
  }

  /**
   * Register a hook to run after a method call.
   *
   * @param methodName Format: "ServiceName.MethodName"
   * @param hook receives (request, response) and returns modified response
   */
  <Req extends Message, Resp extends Message> void after(
      String methodName, AfterHook<Req, Resp> hook) {
    afterHooks.put(methodName, hook);
  }

  /**
   * Execute before hooks for a method.
   *
   * @return modified request, or original if no hook registered
   */
  @SuppressWarnings("unchecked")
  <T extends Message> T executeBefore(String methodName, T request) {
    BeforeHook<T> hook = (BeforeHook<T>) beforeHooks.get(methodName);
    if (hook == null) {
      return request;
    }
    return hook.apply(request);
  }

  /**
   * Execute after hooks for a method.
   *
   * @return modified response, or original if no hook registered
   */
  @SuppressWarnings("unchecked")
  <Req extends Message, Resp extends Message> Resp executeAfter(
      String methodName, Req request, Resp response) {
    AfterHook<Req, Resp> hook = (AfterHook<Req, Resp>) afterHooks.get(methodName);
    if (hook == null) {
      return response;
    }
    return hook.apply(request, response);
  }
}
