// This file was generated by constgen. DO NOT EDIT.

package com.strongdm.api;

// Node Lifecycle States, defining whether a node was last reported online, offline, restarting, etc.
public final class NodeState {
	public final static String NEW = "new";
	public final static String VERIFYING_RESTART = "verifying_restart";
	public final static String AWAITING_RESTART = "awaiting_restart";
	public final static String RESTARTING = "restarting";
	public final static String STARTED = "started";
	public final static String STOPPED = "stopped";
	public final static String DEAD = "dead";
}
