// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protogen. DO NOT EDIT.

package com.strongdm.api;

public class OktaMFAConfig {
  private String apiToken;
  /** The API token to authenticate with when auth_mode is api_token. */
  public String getApiToken() {
    return this.apiToken;
  }
  /** The API token to authenticate with when auth_mode is api_token. */
  public void setApiToken(String in) {
    this.apiToken = in;
  }

  private boolean apiTokenSet;
  /** Indicates if an API token is already stored. */
  public boolean getApiTokenSet() {
    return this.apiTokenSet;
  }
  /** Indicates if an API token is already stored. */
  public void setApiTokenSet(boolean in) {
    this.apiTokenSet = in;
  }

  private String authMode;
  /** The Okta auth mode, one of the OktaAuthMode constants. */
  public String getAuthMode() {
    return this.authMode;
  }
  /** The Okta auth mode, one of the OktaAuthMode constants. */
  public void setAuthMode(String in) {
    this.authMode = in;
  }

  private String clientId;
  /** The Okta client ID to authenticate with when auth_mode is client_credentials. */
  public String getClientId() {
    return this.clientId;
  }
  /** The Okta client ID to authenticate with when auth_mode is client_credentials. */
  public void setClientId(String in) {
    this.clientId = in;
  }

  private boolean multidevicePushEnabled;
  /** Indicates if multidevice push is enabled. */
  public boolean getMultidevicePushEnabled() {
    return this.multidevicePushEnabled;
  }
  /** Indicates if multidevice push is enabled. */
  public void setMultidevicePushEnabled(boolean in) {
    this.multidevicePushEnabled = in;
  }

  private String organizationUrl;
  /** The Okta organization URL. */
  public String getOrganizationUrl() {
    return this.organizationUrl;
  }
  /** The Okta organization URL. */
  public void setOrganizationUrl(String in) {
    this.organizationUrl = in;
  }

  private String privateKeyId;
  /** The key ID (kid) assigned by Okta to the registered public key. */
  public String getPrivateKeyId() {
    return this.privateKeyId;
  }
  /** The key ID (kid) assigned by Okta to the registered public key. */
  public void setPrivateKeyId(String in) {
    this.privateKeyId = in;
  }

  private boolean privateKeyIdSet;
  /**
   * Indicates if a key ID is already stored or explicitly supplied. This allows callers to preserve
   * the existing value when omitted or clear it by sending an empty string with
   * private_key_id_set=true.
   */
  public boolean getPrivateKeyIdSet() {
    return this.privateKeyIdSet;
  }
  /**
   * Indicates if a key ID is already stored or explicitly supplied. This allows callers to preserve
   * the existing value when omitted or clear it by sending an empty string with
   * private_key_id_set=true.
   */
  public void setPrivateKeyIdSet(boolean in) {
    this.privateKeyIdSet = in;
  }

  private String privateKeyPem;
  /** The PEM encoded private key to authenticate with when auth_mode is client_credentials. */
  public String getPrivateKeyPem() {
    return this.privateKeyPem;
  }
  /** The PEM encoded private key to authenticate with when auth_mode is client_credentials. */
  public void setPrivateKeyPem(String in) {
    this.privateKeyPem = in;
  }

  private boolean privateKeyPemSet;
  /** Indicates if a PEM encoded private key is already stored. */
  public boolean getPrivateKeyPemSet() {
    return this.privateKeyPemSet;
  }
  /** Indicates if a PEM encoded private key is already stored. */
  public void setPrivateKeyPemSet(boolean in) {
    this.privateKeyPemSet = in;
  }

  private String userLookup;
  /** The Okta user lookup strategy, one of the OktaUserLookup constants. */
  public String getUserLookup() {
    return this.userLookup;
  }
  /** The Okta user lookup strategy, one of the OktaUserLookup constants. */
  public void setUserLookup(String in) {
    this.userLookup = in;
  }
}
