// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protogen. DO NOT EDIT.

package com.strongdm.api;

/** PeeringGroupResource represents the attachment between a PeeringGroup and a Resource. */
public class PeeringGroupResource {
  private String groupId;
  /** Peering Group ID to which the resource will be attached to. */
  public String getGroupId() {
    return this.groupId;
  }
  /** Peering Group ID to which the resource will be attached to. */
  public void setGroupId(String in) {
    this.groupId = in;
  }

  private String id;
  /** Unique identifier of the Attachment. */
  public String getId() {
    return this.id;
  }
  /** Unique identifier of the Attachment. */
  public void setId(String in) {
    this.id = in;
  }

  private String resourceId;
  /** Resource ID to be attached. */
  public String getResourceId() {
    return this.resourceId;
  }
  /** Resource ID to be attached. */
  public void setResourceId(String in) {
    this.resourceId = in;
  }
}
