// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protogen. DO NOT EDIT.

package com.strongdm.api;

import com.strongdm.api.plumbing.PageIterator;
import com.strongdm.api.plumbing.PageResult;
import com.strongdm.api.plumbing.PeeringGroupNodesGrpc;
import com.strongdm.api.plumbing.PeeringGroupNodesPlumbing;
import com.strongdm.api.plumbing.Plumbing;
import com.strongdm.api.plumbing.Spec.GetRequestMetadata;
import com.strongdm.api.plumbing.Spec.ListRequestMetadata;
import io.grpc.Deadline;
import io.grpc.ManagedChannel;
import java.util.Iterator;
import java.util.List;
import java.util.concurrent.TimeUnit;
import java.util.function.Supplier;

/**
 * PeeringGroupNodes provides the building blocks necessary to obtain attach a node to a peering
 * group.
 */
public class PeeringGroupNodes {
  private final PeeringGroupNodesGrpc.PeeringGroupNodesBlockingStub stub;
  private final Client parent;
  private final Deadline deadline;

  public PeeringGroupNodes(ManagedChannel channel, Client client) {
    this.stub = PeeringGroupNodesGrpc.newBlockingStub(channel);
    this.parent = client;
    this.deadline = null;
  }

  private PeeringGroupNodes(
      PeeringGroupNodesGrpc.PeeringGroupNodesBlockingStub stub, Client client, Deadline deadline) {
    this.stub = stub;
    this.parent = client;
    this.deadline = deadline;
  }

  /**
   * This function returns a copy of the PeeringGroupNodes service which has the given deadline set
   * for all method calls.
   */
  public PeeringGroupNodes withDeadlineAfter(long duration, TimeUnit units) {
    Deadline deadline = Deadline.after(duration, units);
    return new PeeringGroupNodes(this.stub.withDeadline(deadline), this.parent, deadline);
  }
  /** Create attaches a Node to a PeeringGroup */
  public PeeringGroupNodeCreateResponse create(PeeringGroupNode peeringGroupNode)
      throws RpcException {
    PeeringGroupNodesPlumbing.PeeringGroupNodeCreateRequest.Builder builder =
        PeeringGroupNodesPlumbing.PeeringGroupNodeCreateRequest.newBuilder();
    builder.setPeeringGroupNode(Plumbing.convertPeeringGroupNodeToPlumbing(peeringGroupNode));
    PeeringGroupNodesPlumbing.PeeringGroupNodeCreateRequest req = builder.build();
    PeeringGroupNodesPlumbing.PeeringGroupNodeCreateResponse plumbingResponse;
    int tries = 0;
    while (true) {
      try {
        plumbingResponse =
            this.stub
                .withCallCredentials(
                    this.parent.getCallCredentials("PeeringGroupNodes.Create", req))
                .create(req);
      } catch (Exception e) {
        if (this.parent.shouldRetry(tries, e, this.deadline)) {
          tries++;
          try {
            Thread.sleep(this.parent.exponentialBackoff(tries, this.deadline));
          } catch (Exception ignored) {
          }
          continue;
        }
        throw Plumbing.convertExceptionToPorcelain(e);
      }
      break;
    }
    return Plumbing.convertPeeringGroupNodeCreateResponseToPorcelain(plumbingResponse);
  }
  /** Delete detaches a Node to a PeeringGroup. */
  public PeeringGroupNodeDeleteResponse delete(String id) throws RpcException {
    PeeringGroupNodesPlumbing.PeeringGroupNodeDeleteRequest.Builder builder =
        PeeringGroupNodesPlumbing.PeeringGroupNodeDeleteRequest.newBuilder();
    builder.setId((id));
    PeeringGroupNodesPlumbing.PeeringGroupNodeDeleteRequest req = builder.build();
    PeeringGroupNodesPlumbing.PeeringGroupNodeDeleteResponse plumbingResponse;
    int tries = 0;
    while (true) {
      try {
        plumbingResponse =
            this.stub
                .withCallCredentials(
                    this.parent.getCallCredentials("PeeringGroupNodes.Delete", req))
                .delete(req);
      } catch (Exception e) {
        if (this.parent.shouldRetry(tries, e, this.deadline)) {
          tries++;
          try {
            Thread.sleep(this.parent.exponentialBackoff(tries, this.deadline));
          } catch (Exception ignored) {
          }
          continue;
        }
        throw Plumbing.convertExceptionToPorcelain(e);
      }
      break;
    }
    return Plumbing.convertPeeringGroupNodeDeleteResponseToPorcelain(plumbingResponse);
  }
  /** Get reads the information of one peering group to node attachment. */
  public PeeringGroupNodeGetResponse get(String id) throws RpcException {
    PeeringGroupNodesPlumbing.PeeringGroupNodeGetRequest.Builder builder =
        PeeringGroupNodesPlumbing.PeeringGroupNodeGetRequest.newBuilder();
    if (this.parent.snapshotDate != null) {
      GetRequestMetadata.Builder metaBuilder = GetRequestMetadata.newBuilder();
      metaBuilder.setSnapshotAt(Plumbing.convertTimestampToPlumbing(this.parent.snapshotDate));
      builder.setMeta(metaBuilder);
    }
    builder.setId((id));
    PeeringGroupNodesPlumbing.PeeringGroupNodeGetRequest req = builder.build();
    PeeringGroupNodesPlumbing.PeeringGroupNodeGetResponse plumbingResponse;
    int tries = 0;
    while (true) {
      try {
        plumbingResponse =
            this.stub
                .withCallCredentials(this.parent.getCallCredentials("PeeringGroupNodes.Get", req))
                .get(req);
      } catch (Exception e) {
        if (this.parent.shouldRetry(tries, e, this.deadline)) {
          tries++;
          try {
            Thread.sleep(this.parent.exponentialBackoff(tries, this.deadline));
          } catch (Exception ignored) {
          }
          continue;
        }
        throw Plumbing.convertExceptionToPorcelain(e);
      }
      break;
    }
    return Plumbing.convertPeeringGroupNodeGetResponseToPorcelain(plumbingResponse);
  }
  /** List gets a list of peering group node attachments. */
  public Iterable<PeeringGroupNode> list(String filter, Object... args) throws RpcException {
    PeeringGroupNodesPlumbing.PeeringGroupNodeListRequest.Builder builder =
        PeeringGroupNodesPlumbing.PeeringGroupNodeListRequest.newBuilder();
    builder.setFilter(Plumbing.quoteFilterArgs(filter, args));
    ListRequestMetadata.Builder metaBuilder = ListRequestMetadata.newBuilder();
    if (this.parent.pageLimit > 0) {
      metaBuilder.setLimit(this.parent.pageLimit);
    }
    if (this.parent.snapshotDate != null) {
      metaBuilder.setSnapshotAt(Plumbing.convertTimestampToPlumbing(this.parent.snapshotDate));
    }
    builder.setMeta(metaBuilder);

    Supplier<PageResult<PeeringGroupNode>> pageFetcher =
        () -> {
          // Note: this closure captures and reuses the builder to set the next page
          PeeringGroupNodesPlumbing.PeeringGroupNodeListRequest req = builder.build();
          PeeringGroupNodesPlumbing.PeeringGroupNodeListResponse plumbingResponse;
          int tries = 0;
          while (true) {
            try {
              plumbingResponse =
                  this.stub
                      .withCallCredentials(
                          this.parent.getCallCredentials("PeeringGroupNodes.List", req))
                      .list(req);
            } catch (Exception e) {
              if (this.parent.shouldRetry(tries, e, this.deadline)) {
                tries++;
                try {
                  Thread.sleep(this.parent.exponentialBackoff(tries, this.deadline));
                } catch (Exception ignored) {
                }
                continue;
              }
              throw Plumbing.convertExceptionToPorcelain(e);
            }
            break;
          }

          List<PeeringGroupNode> page =
              Plumbing.convertRepeatedPeeringGroupNodeToPorcelain(
                  plumbingResponse.getPeeringGroupNodesList());

          boolean hasNextCursor = plumbingResponse.getMeta().getNextCursor() != "";
          builder.setMeta(
              ListRequestMetadata.newBuilder()
                  .setCursor(plumbingResponse.getMeta().getNextCursor()));

          return new PageResult<PeeringGroupNode>(page, hasNextCursor);
        };

    Iterator<PeeringGroupNode> iterator = new PageIterator<>(pageFetcher);

    return () -> iterator;
  }
}
