// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protogen. DO NOT EDIT.

package com.strongdm.api;

import java.util.Date;

/**
 * Proxy Cluster Keys are authentication keys for all proxies within a cluster. The proxies within a
 * cluster share the same key. One cluster can have multiple keys in order to facilitate key
 * rotation.
 */
public class ProxyClusterKey {
  private Date createdAt;
  /** The timestamp when this key was created. */
  public Date getCreatedAt() {
    return this.createdAt;
  }
  /** The timestamp when this key was created. */
  public void setCreatedAt(Date in) {
    this.createdAt = in;
  }

  private String id;
  /** Unique identifier of the Relay. */
  public String getId() {
    return this.id;
  }
  /** Unique identifier of the Relay. */
  public void setId(String in) {
    this.id = in;
  }

  private Date lastUsedAt;
  /** The timestamp when this key was last used, if at all. */
  public Date getLastUsedAt() {
    return this.lastUsedAt;
  }
  /** The timestamp when this key was last used, if at all. */
  public void setLastUsedAt(Date in) {
    this.lastUsedAt = in;
  }

  private String proxyClusterId;
  /** The ID of the proxy cluster which this key authenticates to. */
  public String getProxyClusterId() {
    return this.proxyClusterId;
  }
  /** The ID of the proxy cluster which this key authenticates to. */
  public void setProxyClusterId(String in) {
    this.proxyClusterId = in;
  }
}
