// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// This file was generated by protogen. DO NOT EDIT.

package com.strongdm.api;

import com.strongdm.api.plumbing.PageIterator;
import com.strongdm.api.plumbing.PageResult;
import com.strongdm.api.plumbing.Plumbing;
import com.strongdm.api.plumbing.QueriesGrpc;
import com.strongdm.api.plumbing.QueriesPlumbing;
import com.strongdm.api.plumbing.Spec.ListRequestMetadata;
import io.grpc.ManagedChannel;
import java.util.Iterator;
import java.util.List;
import java.util.concurrent.TimeUnit;
import java.util.function.Supplier;

/**
 * A Query is a record of a single client request to a resource, such as an SQL query. Long-running
 * SSH, RDP, or Kubernetes interactive sessions also count as queries. The Queries service is
 * read-only.
 */
public class Queries {
  private final QueriesGrpc.QueriesBlockingStub stub;
  private final Client parent;

  public Queries(ManagedChannel channel, Client client) {

    this.stub = QueriesGrpc.newBlockingStub(channel);
    this.parent = client;
  }

  private Queries(QueriesGrpc.QueriesBlockingStub stub, Client client) {
    this.stub = stub;
    this.parent = client;
  }

  /**
   * This function returns a copy of the Queries service which has the given deadline set for all
   * method calls.
   */
  public Queries withDeadlineAfter(long duration, TimeUnit units) {
    return new Queries(this.stub.withDeadlineAfter(duration, units), this.parent);
  }
  /** List gets a list of Queries matching a given set of criteria. */
  public Iterable<Query> list(String filter, Object... args) throws RpcException {
    QueriesPlumbing.QueryListRequest.Builder builder =
        QueriesPlumbing.QueryListRequest.newBuilder();
    builder.setFilter(Plumbing.quoteFilterArgs(filter, args));
    ListRequestMetadata.Builder metaBuilder = ListRequestMetadata.newBuilder();
    Object pageSizeOption = this.parent.testOptions.get("PageSize");
    if (pageSizeOption instanceof Integer) {
      metaBuilder.setLimit((int) pageSizeOption);
    }
    if (this.parent.snapshotDate != null) {
      metaBuilder.setSnapshotAt(Plumbing.convertTimestampToPlumbing(this.parent.snapshotDate));
    }
    builder.setMeta(metaBuilder);

    Supplier<PageResult<Query>> pageFetcher =
        () -> {
          // Note: this closure captures and reuses the builder to set the next page
          QueriesPlumbing.QueryListRequest req = builder.build();
          QueriesPlumbing.QueryListResponse plumbingResponse;
          int tries = 0;
          while (true) {
            try {
              plumbingResponse =
                  this.stub
                      .withCallCredentials(this.parent.getCallCredentials("Queries.List", req))
                      .list(req);
            } catch (Exception e) {
              if (this.parent.shouldRetry(tries, e)) {
                tries++;
                this.parent.jitterSleep(tries);
                continue;
              }
              throw Plumbing.convertExceptionToPorcelain(e);
            }
            break;
          }

          List<Query> page =
              Plumbing.convertRepeatedQueryToPorcelain(plumbingResponse.getQueriesList());

          boolean hasNextCursor = plumbingResponse.getMeta().getNextCursor() != "";
          builder.setMeta(
              ListRequestMetadata.newBuilder()
                  .setCursor(plumbingResponse.getMeta().getNextCursor()));

          return new PageResult<Query>(page, hasNextCursor);
        };

    Iterator<Query> iterator = new PageIterator<>(pageFetcher);

    return () -> iterator;
  }
}
