// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protogen. DO NOT EDIT.

package com.strongdm.api;

import java.time.Duration;

/**
 * A ReplayChunkEvent represents a single event within a query replay. The timing information
 * included in each ReplayChunkEvent may be used to replay a session in real time.
 */
public class ReplayChunkEvent {
  private byte[] data;
  /** The raw data of the ReplayChunkEvent. */
  public byte[] getData() {
    return this.data;
  }
  /** The raw data of the ReplayChunkEvent. */
  public void setData(byte[] in) {
    this.data = in;
  }

  private Duration duration;
  /** The time duration over which the data in this ReplayChunkEvent was transferred. */
  public Duration getDuration() {
    return this.duration;
  }
  /** The time duration over which the data in this ReplayChunkEvent was transferred. */
  public void setDuration(Duration in) {
    this.duration = in;
  }
}
