// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protogen. DO NOT EDIT.

package com.strongdm.api;

import com.strongdm.api.plumbing.PageIterator;
import com.strongdm.api.plumbing.PageResult;
import com.strongdm.api.plumbing.Plumbing;
import com.strongdm.api.plumbing.ReplaysGrpc;
import com.strongdm.api.plumbing.ReplaysPlumbing;
import com.strongdm.api.plumbing.Spec.ListRequestMetadata;
import io.grpc.ManagedChannel;
import java.util.Iterator;
import java.util.List;
import java.util.concurrent.TimeUnit;
import java.util.function.Supplier;

/**
 * A Replay captures the data transferred over a long-running SSH, RDP, or Kubernetes interactive
 * session (otherwise referred to as a query). The Replays service is read-only.
 */
public class Replays {
  private final ReplaysGrpc.ReplaysBlockingStub stub;
  private final Client parent;

  public Replays(ManagedChannel channel, Client client) {

    this.stub = ReplaysGrpc.newBlockingStub(channel);
    this.parent = client;
  }

  private Replays(ReplaysGrpc.ReplaysBlockingStub stub, Client client) {
    this.stub = stub;
    this.parent = client;
  }

  /**
   * This function returns a copy of the Replays service which has the given deadline set for all
   * method calls.
   */
  public Replays withDeadlineAfter(long duration, TimeUnit units) {
    return new Replays(this.stub.withDeadlineAfter(duration, units), this.parent);
  }
  /** List gets a list of ReplayChunks for the Query ID specified by the filter criteria. */
  public Iterable<ReplayChunk> list(String filter, Object... args) throws RpcException {
    ReplaysPlumbing.ReplayListRequest.Builder builder =
        ReplaysPlumbing.ReplayListRequest.newBuilder();
    builder.setFilter(Plumbing.quoteFilterArgs(filter, args));
    ListRequestMetadata.Builder metaBuilder = ListRequestMetadata.newBuilder();
    Object pageSizeOption = this.parent.testOptions.get("PageSize");
    if (pageSizeOption instanceof Integer) {
      metaBuilder.setLimit((int) pageSizeOption);
    }
    if (this.parent.snapshotDate != null) {
      metaBuilder.setSnapshotAt(Plumbing.convertTimestampToPlumbing(this.parent.snapshotDate));
    }
    builder.setMeta(metaBuilder);

    Supplier<PageResult<ReplayChunk>> pageFetcher =
        () -> {
          // Note: this closure captures and reuses the builder to set the next page
          ReplaysPlumbing.ReplayListRequest req = builder.build();
          ReplaysPlumbing.ReplayListResponse plumbingResponse;
          int tries = 0;
          while (true) {
            try {
              plumbingResponse =
                  this.stub
                      .withCallCredentials(this.parent.getCallCredentials("Replays.List", req))
                      .list(req);
            } catch (Exception e) {
              if (this.parent.shouldRetry(tries, e)) {
                tries++;
                this.parent.jitterSleep(tries);
                continue;
              }
              throw Plumbing.convertExceptionToPorcelain(e);
            }
            break;
          }

          List<ReplayChunk> page =
              Plumbing.convertRepeatedReplayChunkToPorcelain(plumbingResponse.getChunksList());

          boolean hasNextCursor = plumbingResponse.getMeta().getNextCursor() != "";
          builder.setMeta(
              ListRequestMetadata.newBuilder()
                  .setCursor(plumbingResponse.getMeta().getNextCursor()));

          return new PageResult<ReplayChunk>(page, hasNextCursor);
        };

    Iterator<ReplayChunk> iterator = new PageIterator<>(pageFetcher);

    return () -> iterator;
  }
}
