// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protogen. DO NOT EDIT.

package com.strongdm.api;

/** RequestableResource is a resource that can be requested via an AccessRequestConfig */
public class RequestableResource {
  private String access;
  /** The current state of the user's access to the resources */
  public String getAccess() {
    return this.access;
  }
  /** The current state of the user's access to the resources */
  public void setAccess(String in) {
    this.access = in;
  }

  private String authentication;
  /** The type of authentication for the resource */
  public String getAuthentication() {
    return this.authentication;
  }
  /** The type of authentication for the resource */
  public void setAuthentication(String in) {
    this.authentication = in;
  }

  private boolean healthy;
  /** The health check status of the reasource */
  public boolean getHealthy() {
    return this.healthy;
  }
  /** The health check status of the reasource */
  public void setHealthy(boolean in) {
    this.healthy = in;
  }

  private String id;
  /** The resource id. */
  public String getId() {
    return this.id;
  }
  /** The resource id. */
  public void setId(String in) {
    this.id = in;
  }

  private String name;
  /** The resource name. */
  public String getName() {
    return this.name;
  }
  /** The resource name. */
  public void setName(String in) {
    this.name = in;
  }

  private java.util.Map<String, String> tags;
  /** Any tags attached to this resource */
  public java.util.Map<String, String> getTags() {
    java.util.Map<String, String> m = new java.util.HashMap<String, String>();
    if (this.tags != null) {
      m.putAll(this.tags);
    }
    return m;
  }
  /** Any tags attached to this resource */
  public void setTags(java.util.Map<String, String> in) {
    if (in == null) {
      this.tags = null;
      return;
    }
    this.tags = new java.util.HashMap<String, String>();
    this.tags.putAll(in);
  }

  private String type;
  /** The resource type */
  public String getType() {
    return this.type;
  }
  /** The resource type */
  public void setType(String in) {
    this.type = in;
  }
}
