// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protogen. DO NOT EDIT.

package com.strongdm.api;

/** A SecretEngine is managing secrets in SecretStores. */
public interface SecretEngine {
  /** Returns the unique identifier of the SecretEngine. */
  String getId();
  /** Returns the name of the SecretEngine. */
  String getName();
  /** Sets the name of the SecretEngine. */
  void setName(String name);
  /** Returns the tags of the SecretEngine. */
  java.util.Map<String, String> getTags();
  /** Sets the tags of the SecretEngine. */
  void setTags(java.util.Map<String, String> tags);
  /** Returns the secret store id of the SecretEngine. */
  String getSecretStoreId();
  /** Sets the secret store id of the SecretEngine. */
  void setSecretStoreId(String secretStoreId);
  /** Returns the secret store root path of the SecretEngine. */
  String getSecretStoreRootPath();
  /** Sets the secret store root path of the SecretEngine. */
  void setSecretStoreRootPath(String secretStoreRootPath);
  /** Returns the public key of the SecretEngine. */
  byte[] getPublicKey();
  /** Sets the public key of the SecretEngine. */
  void setPublicKey(byte[] publicKey);
  /** Returns the node selector of the SecretEngine. */
  String getNodeSelector();
  /** Sets the node selector of the SecretEngine. */
  void setNodeSelector(String nodeSelector);
  /** Returns the key rotation interval days of the SecretEngine. */
  int getKeyRotationIntervalDays();
  /** Sets the key rotation interval days of the SecretEngine. */
  void setKeyRotationIntervalDays(int keyRotationIntervalDays);
}
