// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protogen. DO NOT EDIT.

package com.strongdm.api;

/**
 * A SecretStore is a server where resource secrets (passwords, keys) are stored. Coming soon
 * support for HashiCorp Vault and AWS Secret Store. Contact support@strongdm.com to request access
 * to the beta.
 */
public interface SecretStore {
  /** Returns the unique identifier of the SecretStore. */
  String getId();
  /** Returns the tags of the SecretStore. */
  java.util.Map<String, String> getTags();
  /** Sets the tags of the SecretStore. */
  void setTags(java.util.Map<String, String> tags);
  /** Returns the name of the SecretStore. */
  String getName();
  /** Sets the name of the SecretStore. */
  void setName(String name);
}
