// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protogen. DO NOT EDIT.

package com.strongdm.api;

import java.util.Date;
import java.util.List;

/**
 * SecretStoreHealth denotes a secret store's health status. Note a secret store is not healthy in
 * terms of a simple boolean, but rather healthy with respect to a particular node or set of nodes.
 */
public class SecretStoreHealth {
  private Date changedAt;
  /** The time when the status last changed */
  public Date getChangedAt() {
    return this.changedAt;
  }
  /** The time when the status last changed */
  public void setChangedAt(Date in) {
    this.changedAt = in;
  }

  private Date checkedAt;
  /** The time when the status was last checked by the node */
  public Date getCheckedAt() {
    return this.checkedAt;
  }
  /** The time when the status was last checked by the node */
  public void setCheckedAt(Date in) {
    this.checkedAt = in;
  }

  private String error;
  /**
   * The error associated with this health check, if it occurred after reachability checks
   * succeeded.
   */
  public String getError() {
    return this.error;
  }
  /**
   * The error associated with this health check, if it occurred after reachability checks
   * succeeded.
   */
  public void setError(String in) {
    this.error = in;
  }

  private List<String> flags;
  /** Any specific status or error flags associated with this health check. */
  public List<String> getFlags() {
    return this.flags;
  }
  /** Any specific status or error flags associated with this health check. */
  public void setFlags(List<String> in) {
    this.flags = in;
  }

  private String nodeId;
  /** Associated node id for this health */
  public String getNodeId() {
    return this.nodeId;
  }
  /** Associated node id for this health */
  public void setNodeId(String in) {
    this.nodeId = in;
  }

  private String reachability;
  /** The error associated with this health check, if it occurred during reachability checks. */
  public String getReachability() {
    return this.reachability;
  }
  /** The error associated with this health check, if it occurred during reachability checks. */
  public void setReachability(String in) {
    this.reachability = in;
  }

  private String secretStoreId;
  /** Associated secret store for this health */
  public String getSecretStoreId() {
    return this.secretStoreId;
  }
  /** Associated secret store for this health */
  public void setSecretStoreId(String in) {
    this.secretStoreId = in;
  }

  private String status;
  /** The status of the link between the node and secret store */
  public String getStatus() {
    return this.status;
  }
  /** The status of the link between the node and secret store */
  public void setStatus(String in) {
    this.status = in;
  }
}
