// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// This file was generated by protogen. DO NOT EDIT.

package com.strongdm.api;

/**
 * A SnapshotRemoteIdentityGroups exposes the read only methods of the RemoteIdentityGroups service
 * for historical queries.
 */
public interface SnapshotRemoteIdentityGroups {
  /** Get reads one RemoteIdentityGroup by ID. */
  public RemoteIdentityGroupGetResponse get(String id) throws RpcException;
  /** List gets a list of RemoteIdentityGroups matching a given set of criteria. */
  public Iterable<RemoteIdentityGroup> list(String filter, Object... args) throws RpcException;
}
