// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protogen. DO NOT EDIT.

package com.strongdm.api;

/** SnapshotClient exposes methods to query historical records at a provided timestamp. */
public class SnapshotClient {
  private Client parent;

  protected SnapshotClient(Client parent) {
    this.parent = parent;
  }
  /** AccessRequests are requests for access to a resource that may match a Workflow. */
  public SnapshotAccessRequests accessRequests() {
    return this.parent.accessRequests;
  }
  /** AccountAttachments assign an account to a role. */
  public SnapshotAccountAttachments accountAttachments() {
    return this.parent.accountAttachments;
  }
  /**
   * AccountGrants assign a resource directly to an account, giving the account the permission to
   * connect to that resource.
   */
  public SnapshotAccountGrants accountGrants() {
    return this.parent.accountGrants;
  }
  /**
   * AccountPermissions records the granular permissions accounts have, allowing them to execute
   * relevant commands via StrongDM's APIs.
   */
  public SnapshotAccountPermissions accountPermissions() {
    return this.parent.accountPermissions;
  }
  /**
   * AccountResources enumerates the resources to which accounts have access. The AccountResources
   * service is read-only.
   */
  public SnapshotAccountResources accountResources() {
    return this.parent.accountResources;
  }
  /**
   * Accounts are users that have access to strongDM. There are two types of accounts: 1. **Users:**
   * humans who are authenticated through username and password or SSO. 2. **Service Accounts:**
   * machines that are authenticated using a service token. 3. **Tokens** are access keys with
   * permissions that can be used for authentication.
   */
  public SnapshotAccounts accounts() {
    return this.parent.accounts;
  }
  /** An AccountGroup links an account and a group. */
  public SnapshotAccountsGroups accountsGroups() {
    return this.parent.accountsGroups;
  }
  /** ApprovalWorkflowApprovers link approval workflow approvers to an ApprovalWorkflowStep */
  @Deprecated
  public SnapshotApprovalWorkflowApprovers approvalWorkflowApprovers() {
    return this.parent.approvalWorkflowApprovers;
  }
  /** ApprovalWorkflowSteps link approval workflow steps to an ApprovalWorkflow */
  @Deprecated
  public SnapshotApprovalWorkflowSteps approvalWorkflowSteps() {
    return this.parent.approvalWorkflowSteps;
  }
  /**
   * ApprovalWorkflows are the mechanism by which requests for access can be viewed by authorized
   * approvers and be approved or denied.
   */
  public SnapshotApprovalWorkflows approvalWorkflows() {
    return this.parent.approvalWorkflows;
  }
  /**
   * A Role has a list of access rules which determine which Resources the members of the Role have
   * access to. An Account can be a member of multiple Roles via AccountAttachments.
   */
  public SnapshotRoles roles() {
    return this.parent.roles;
  }
  /** A Group is a set of principals. */
  public SnapshotGroups groups() {
    return this.parent.groups;
  }
  /** A GroupRole is an assignment of a Group to a Role. */
  public SnapshotGroupsRoles groupsRoles() {
    return this.parent.groupsRoles;
  }
  /**
   * IdentityAliases assign an alias to an account within an IdentitySet. The alias is used as the
   * username when connecting to a identity supported resource.
   */
  public SnapshotIdentityAliases identityAliases() {
    return this.parent.identityAliases;
  }
  /**
   * A IdentitySet is a named grouping of Identity Aliases for Accounts. An Account's relationship
   * to a IdentitySet is defined via IdentityAlias objects.
   */
  public SnapshotIdentitySets identitySets() {
    return this.parent.identitySets;
  }
  /**
   * Nodes make up the StrongDM network, and allow your users to connect securely to your resources.
   * There are three types of nodes: 1. **Relay:** creates connectivity to your datasources, while
   * maintaining the egress-only nature of your firewall 2. **Gateway:** a relay that also listens
   * for connections from StrongDM clients 3. **Proxy Cluster:** a cluster of workers that together
   * mediate access from clients to resources
   */
  public SnapshotNodes nodes() {
    return this.parent.nodes;
  }
  /**
   * Policies are the collection of one or more statements that enforce fine-grained access control
   * for the users of an organization.
   */
  public SnapshotPolicies policies() {
    return this.parent.policies;
  }
  /**
   * Proxy Cluster Keys are authentication keys for all proxies within a cluster. The proxies within
   * a cluster share the same key. One cluster can have multiple keys in order to facilitate key
   * rotation.
   */
  public SnapshotProxyClusterKeys proxyClusterKeys() {
    return this.parent.proxyClusterKeys;
  }
  /**
   * RemoteIdentities assign a resource directly to an account, giving the account the permission to
   * connect to that resource.
   */
  @Deprecated
  public SnapshotRemoteIdentities remoteIdentities() {
    return this.parent.remoteIdentities;
  }
  /**
   * A RemoteIdentityGroup is a named grouping of Remote Identities for Accounts. An Account's
   * relationship to a RemoteIdentityGroup is defined via RemoteIdentity objects.
   */
  @Deprecated
  public SnapshotRemoteIdentityGroups remoteIdentityGroups() {
    return this.parent.remoteIdentityGroups;
  }
  /**
   * Resources are databases, servers, clusters, websites, or clouds that strongDM delegates access
   * to.
   */
  public SnapshotResources resources() {
    return this.parent.resources;
  }
  /**
   * RoleResources enumerates the resources to which roles have access. The RoleResources service is
   * read-only.
   */
  public SnapshotRoleResources roleResources() {
    return this.parent.roleResources;
  }
  /** SecretStores are servers where resource secrets (passwords, keys) are stored. */
  public SnapshotSecretStores secretStores() {
    return this.parent.secretStores;
  }
  /**
   * WorkflowApprovers is an account or a role with the ability to approve requests bound to a
   * workflow.
   */
  public SnapshotWorkflowApprovers workflowApprovers() {
    return this.parent.workflowApprovers;
  }
  /**
   * WorkflowRole links a role to a workflow. The linked roles indicate which roles a user must be a
   * part of to request access to a resource via the workflow.
   */
  public SnapshotWorkflowRoles workflowRoles() {
    return this.parent.workflowRoles;
  }
  /**
   * Workflows are the collection of rules that define the resources to which access can be
   * requested, the users that can request that access, and the mechanism for approving those
   * requests which can either be automatic approval or a set of users authorized to approve the
   * requests.
   */
  public SnapshotWorkflows workflows() {
    return this.parent.workflows;
  }
}
