// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protogen. DO NOT EDIT.

package com.strongdm.api;

public class Tag {
  private String name;
  /** The name or key of this tag. Each name can only refer to one value on a tagged entity. */
  public String getName() {
    return this.name;
  }
  /** The name or key of this tag. Each name can only refer to one value on a tagged entity. */
  public void setName(String in) {
    this.name = in;
  }

  private String value;
  /** The value of this tag. */
  public String getValue() {
    return this.value;
  }
  /** The value of this tag. */
  public void setValue(String in) {
    this.value = in;
  }
}
