// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protogen. DO NOT EDIT.

package com.strongdm.api;

/** WorkflowApprover is an account with the ability to approve requests bound to a workflow. */
public class WorkflowApprover {
  private String approverId;
  /** The approver id. */
  public String getApproverId() {
    return this.approverId;
  }
  /** The approver id. */
  public void setApproverId(String in) {
    this.approverId = in;
  }

  private String workflowId;
  /** The workflow id. */
  public String getWorkflowId() {
    return this.workflowId;
  }
  /** The workflow id. */
  public void setWorkflowId(String in) {
    this.workflowId = in;
  }
}
